### PR TITLE
internal: Use rustc-hash in more places

### PR DESCRIPTION
**Pull request by lnicola**
I think there's still ~~a couple~~ a lot of these left, some in tests and the proc macro server.

### CODE REVIEW

**Comment by Veykril** [comment]
Ideally we should add a clippy.toml and the disallowed-types lint with that set up to forbid using plain `HashMap`, now that lints in Cargo.toml are a thing

**Comment by lnicola** [comment]
Good idea, I forgot that was a thing. It feels like the hardest part is bikeshedding them, e.g. what should we use in `lsp-server`?

**Comment by Veykril** [comment]
Hmm, I guess lsp-server is the exception, it should be fine to use in there?

**Comment by lnicola** [comment]
It also doesn't seem to work very well with derive macros. Anyway, I'll give it a try.

**Comment by Veykril** [comment]
what derive macros we use emit hashmap related things? 🤔  or was that more a general note, not specific to r-a's codebase

**Comment by lnicola** [comment]
We have some hashmaps in `lsp_ext` and i think we have to move them into a submodule to allow the lint there, because they derive Serialize.

**Comment by Veykril** [comment]
Might as well just replace those with `FxHashMap` as well since we have the dependency there.

**Comment by lnicola** [comment]
I don't remember exactly why that didn't work, they might end up in `lsp-types` or something like that.

**Comment by Veykril** [comment]
I see, well excluding that module should be fine anyways.

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/16470 supersedes this

**Pull request closed without merging**
