### PR TITLE
Add assist for filling fields by replacing ellipsis in record syntax

### PR DESCRIPTION
**Pull request by dfireBird**
I'm not sure if the tests cover the most cases, I'll add more if suggested.

### CODE REVIEW

**Review by Veykril — COMMENTED** [review]
A test case for a struct or enum variant that is generated from a macro would be good (to check whether it works there, or whether it is correctly inapplicable)

**Comment by dfireBird** [comment]
I have never worked on macros (i.e the one writing macros not using them), so if you don't mind, can you point out a snippet somewhere and see how tests can be done?

**Comment by Veykril** [comment]
Yes, that is exactly a test case I had in mind

**Comment by dfireBird** [comment]
I added those tests along with a new check and corresponding test.

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Pull request merged**
