### PR TITLE
Sync from downstream

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by Veykril** [comment]
Fwiw, this brought the mir bodies back to fail @HKalbasi, i imagine thats because of the fmt argument changes which match latest nightly, but not current stable. Kind of fun how r-a actually breaks because of implementation detail changes 🙂 Are those types lang items? If yes we could maybe somehow make this emit lang items to get around that.

**Comment by lnicola** [comment]
Even before, our expansion was [slightly different](https://github.com/rust-lang/rust-analyzer/pull/14820/files) from that of rustc, but I didn't really understand why :pensive:.

**Comment by Veykril** [comment]
The previous impl was mainly done to satisfy type inference for macro expression as a whole I think

**Comment by Veykril** [comment]
That remidns me I played around with the concept of lang item paths, wonder if I still have that stash/branch

**Comment by HKalbasi** [comment]
Ah, I missed the ping, and saw the ping now that I come to this to see what breaks the mir. Yes, it's the `Argument` change, and it isn't just the mir, the unknown types are also significantly increased, and I guess it may affect some other ide features in a bad way.

I don't see how it is possible to emit lang item paths in macro expanding, but if it is possible to make it working, it is lang item (at least it was in the old version) so I guess there is no problem from this side.

But there is a more general problem here, syncing builtin proc-macro implementations with the rustc, which the lang item path solution is not always available for it. An idealistic solution is to share the implementation with the installed rustc somehow, or make them simple proc-macros. A realistic approach is to conditionally expand builtin macros based on the rustc target version, or just reverting this and re applying it when it hits stable. #14846 is maybe also related.

**Comment by Veykril** [comment]
> I don't see how it is possible to emit lang item paths in macro expanding, 

We would basically allow some special syntax that we'd interpret as a lang item path, something like `lang # lang_item_name`

>  A realistic approach is to conditionally expand builtin macros based on the rustc target version

That's not a realistic approach, then we are back to having to maintain multiple versions of things which we don't want. The way I see it, we either need to ask upstream to make anything that's implementation detail emitted by builtin macros lang items so the names changing doesn't matter or have them be turned into proper proc-macros whose dylibs are shipped with the toolchain.

**Comment by HKalbasi** [comment]
> We would basically allow some special syntax that we'd interpret as a lang item path, something like lang # lang_item_name

Another problem here is that `Argument` is a lang item, but `Argument::new` is what we want so it wouldn't work with current lang paths.

> That's not a realistic approach, then we are back to having to maintain multiple versions of things which we don't want.

We could drop support when it passed some time, and keep only e.g. two latest stable. But okay, let's focus on the lang paths or just drop it until it hits stable.

> we either need to ask upstream to make anything that's implementation detail emitted by builtin macros lang items so the names changing doesn't matter

What I understand from https://github.com/rust-lang/rust/issues/99012 is that it probably wouldn't end in naming changes only. What we can ask is to keeping the old version working for some time.

> or have them be turned into proper proc-macros whose dylibs are shipped with the toolchain.

I like this, but I don't think it would work with `format_args!` as it is too special. It can probably work for other builtin macros, and the less builtin macro, the better. But it would also probably makes some headaches (for one time, hopefully) for us as we don't support std lib dependencies (by the way, is there any news on that issue?)

**Comment by Veykril** [comment]
> Another problem here is that Argument is a lang item, but Argument::new is what we want so it wouldn't work with current lang paths.

It could if we allowed something like `lang#foo::new` (that is the lang#lang_name is treated as a path segment)

> I like this, but I don't think it would work with format_args! as it is too special. 

Right, `format_args` is an eager macro so that wouldn't work as a proc-macro yet... (but soon, there is a nightly feature for that)

**Comment by HKalbasi** [comment]
> Right, format_args is an eager macro so that wouldn't work as a proc-macro yet... (but soon, there is a nightly feature for that)

The `format_args!("{a}")` also couldn't be implemented in proc macros due hygienic I think.

**Comment by Veykril** [comment]
>  (by the way, is there any news on that issue?)

forgot to reply to this, no news there

**Comment by HKalbasi** [comment]
The `format_args` is broken even on nightly. The problem is that `Argument` is defined inside `core::fmt::rt` which is a private module so even if we use `core::fmt::rt::Argument` (we are currently using `core::fmt::Argument`) it wouldn't work. So it seems lang paths are the only way to access that. We need to either make the lang paths a special ast node, or make the entire `format_args!()` a special ast node similar to what rustc does.

**Comment by Veykril** [comment]
>  or make the entire format_args!() a special ast node similar to what rustc does.

This I never understood how they do since you need to resolve the path first before knowing if its a format_args invocation, but resolution obviously happens after AST building.

**Comment by HKalbasi** [comment]
I think `format_args!()` is still a macro, it just will be expanded to the special ast node.

**Pull request merged**
