### PR TITLE
Move rust-analyzer manual to mdbook

### LINKED ISSUE #9504: Manual needs to be more helpful, friendly, and better organized
rust-analyzer manual is pretty long: https://rust-analyzer.github.io/manual.html

It's useful as a reference, but is quite intimidating if you want to learn the tool. We should improve this, both in terms of logical organization, and in terms of HTML&CSS rendering. I am not experienced with it, so help would be much appreciated. 

I think ideally the manual shows a short pit of success, while giving the links to in-depth reference material. Here's a structure I have in mind:

First is quick start, which suggests choosing an editor (VS Code, Vim, Emacs). For a specific editor, we have a single blessed setup. After the setup, we have a short section show-casing the most important features (worksapce symbol, go to definiton, extend selection, running tests, triggering assists). This should be duplicated for editor, and serves two purposes -- teaches about the features and allows the new user to verify if the stuff is working. Aftre quick start and show case, we show how to configure rust-analyzer in the specific editor. After that, we show alterntive setups

After per-editor quick start, we probably want to re-create show case, with the emprasis on how it looks and why it is useful, rather than on which shourtcur do you use to trigger this. 

After universal show-case, we should have an index of features, which leads to specific pages for diagnostics, assists, etc.

After that, we should have troubleshooting and other stuff. 

As I've said, I am not an expert at this: if you think you see a better way to do this, feel free to suggest. The source for manual lives here: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user.

It is render to a web document here: https://github.com/rust-analyzer/rust-analyzer.github.io

The code to move the manual from the first place to the second place is here: https://github.com/rust-analyzer/rust-analyzer/blob/91bfa4b154a9776a57f25071f03e68d4f9f5ef35/xtask/src/release.rs#L25-L50

### PR DESCRIPTION
**Pull request by joshrotenberg**
This refreshes the asciidoc manual to use [mdbook](https://rust-lang.github.io/mdBook).

See responses/ideas in #9504.

Currently a work in progress. If this seems like the right direction, I'll continue with the list below.

TODO:

- [X] For now, verbatim copy content from current manual to corresponding markdown file in `manual`.
- [ ] Figure out how to deal with generated content.
    - [ ] `generated_diagnostics`  - crates/ide-diagnostics/src/tests/sourcegen.rs 
    - [ ] `generated_features` - crates/rust-analyzer/tests/slow-tests/sourcegen.rs
    - [ ] `generated_config` - crates/rust-analyzer/src/config.rs
    - [ ] `generated_assists` - crates/ide-assists/src/tests/sourcegen.rs
- [ ] Move landing page to introduction.
- [ ] Add Quickstart.
- [ ] Copy over `docs/dev` md files to `manual/src/contributing`.  
- [ ] Figure out changes needed for deployment.
- [ ] Add docs on how to build/test/run/modify book.

Fixes #9504.

### CODE REVIEW

**Comment by joshrotenberg** [comment]
Screen Shot 2021-11-17 at 6 27 52 PM

**Comment by Veykril** [comment]
I apologize that no one has gotten back to the PR after *7* months, looks like it feel off of everyone's radar. With that said, are you still interested in this PR? Then I'd take a look at what you've got here and commit some time to review/discussion.

**Comment by joshrotenberg** [comment]
> I apologize that no one has gotten back to the PR after _7_ months, looks like it feel off of everyone's radar. With that said, are you still interested in this PR? Then I'd take a look at what you've got here and commit some time to review/discussion.

No need to apologize, I understand. I’m definitely still interested. I can take another look at it and remember how I left it this week.

**Comment by joshrotenberg** [comment]
Ok, getting back to this. If you like this approach, I can go through and move the current static content from the docs into the new mdbook/markdown format, and then we can discuss how to manage the generated content, as well as any changes/updates you'd like to make to the contents. I may make some editorial updates while I move things over where appropriate. Why don't I do a couple of sections and then we can review and see if you're happy with how it's turning out, and go from there.

**Comment by Veykril** [comment]
Ye I think this looks good, as the issue outlines we should think a bit about the landing page/front page later on but I don't think that impacts the books structure so that's something for later.

Sounds like a plan 👍

**Comment by joshrotenberg** [comment]
Ok, I think this PR is at the point where the remaining changes start touching a lot more files (mostly the generated stuff, of course), so the question is this: would it be preferable to have this overall documentation change (moving to mdbook, I mean) be a process over several PRs (say, this one for *just* new content and another for the cutover) or just one PR that has all the changes?

**Comment by joshrotenberg** [comment]
Screen Shot 2022-08-05 at 8 55 50 PM

Quick peek at how the features page looks. I'll try to get the latest deployed to gh pages on my fork to make it easier to see the current state.

**Comment by joshrotenberg** [comment]
OK! The last big round of updates takes the `Features` page out of ascii doc and into markdown. This involved touching quite a few files, almost all of which was moving from adoc to md in the comments that are parsed. Fortunately, there is a fair amount of crossover. There were also the small code changes required to write the markdown file. 

 I had originally stubbed out a single page per feature. The benefit of this is that we get the full list in the navigation markdown. Since the current process generates to a single file, though, it made more sense to stick with that for now I think, so I added a TOC to the top of the Features page. It's ... ok. I think it's a detail that can potentially get fixed later on.

In regards to my previous comment, making it so that the old and new manual can coexist seems like more work than necessary, so I'm going to plan on making this PR a clean cutover unless someone disagrees. I'll go through and get the other generated sections moved over as well.

**Comment by Veykril** [comment]
Ah I never asked, should I take a look by now or are you still moving some things around?

**Comment by joshrotenberg** [comment]
> Ah I never asked, should I take a look by now or are you still moving some things around?

Still some stuff to work on, had to take a break for other things, but I should be able to get back to it soon.

**Comment by Veykril** [comment]
No rush

**Comment by joshrotenberg** [comment]
Had some environment issues, decided to start fresh with a better conversion process. See https://github.com/rust-lang/rust-analyzer/pull/13316

**Pull request closed without merging**
