### PR TITLE
fix: Fix some typos in `StructFlags`

### PR DESCRIPTION
**Pull request by HKalbasi**
And a question: what is the benefit of storing things like `IS_BOX` in struct flags over using `lang_attr`?

### CODE REVIEW

**Comment by lnicola** [comment]
> thread 'main' panicked at 'internal error: entered unreachable code: Overloaded deref is not a projection', crates/hir-ty/src/mir.rs:119:21

Huh, that's new.

**Comment by Veykril** [comment]
> And a question: what is the benefit of storing things like `IS_BOX` in struct flags over using `lang_attr`?

Cheaper to check, using `lang_attr` directly requires parsing attributes, and given at least the box check is used for auto-deref it should make it worth it imo.

**Comment by HKalbasi** [comment]
> Cheaper to check, using lang_attr directly requires parsing attributes, and given at least the box check is used for auto-deref it should make it worth it imo.

What about a query for lang attribute of an item? It would be a bit nicer and more general.

**Comment by HKalbasi** [comment]
> box check is used for auto-deref it should make it worth it imo.

By the way, this wasn't doing anything before this PR, and it was handled using normal `Deref` impl for box. But I would like to keep it since it is nice for mir to have box deref marked as builtin.

**Comment by Veykril** [comment]
> What about a query for lang attribute of an item? It would be a bit nicer and more general.

I don't see much value from this, at least now right now. Also `StructFlags` are cheap to store (currently they are effectively free I think due to padding in the containing struct even), a query will add more dependency tracking and more caching again.

**Pull request merged**
