### PR TITLE
Tweak Gentoo instructions

### PR DESCRIPTION
**Pull request by lnicola**
CC https://github.com/rust-lang/rust-analyzer/pull/15922#discussion_r1398224723

### CODE REVIEW

**Comment by paul-jewell** [comment]
@lnicola: Quick follow up from the Gentoo guru repository maintainer: 

> There's absolutely no merit in having a dedicated ebuild for rust-analyzer since it was added as a use flag to the official ebuilds. Maybe it would make sense if there would be a possibility of making it a live ebuild, because you wouldn't have to update it every time a new release of rust analyzer comes out (Gentoo's support for rust live ebuilds isn't great, as I've last checked). But even then, there's rustup available with which you don't have to constantly compile anything or maintain anything (rust-analyzer is just too actively developed!).
> What you did in the PR is fine, just mention the possibility of installing rustup on Gentoo and it'll be perfect!

Based on this, I will add an additional pull request including the possibility to install via rustup.

**Comment by lnicola** [comment]
@paul-jewell just curious, where is that from? I couldn't find an issue on the GURU tracker.

**Comment by paul-jewell** [comment]
An email from the maintainer who created/maintained the package on the guru repository - I contacted him directly.

**Comment by lnicola** [comment]
I see.

> But even then, there's rustup available with which you don't have to constantly compile anything or maintain anything (rust-analyzer is just too actively developed!).

Strange words coming from a Gentoo maintainer (I wouldn't have been happy about this when I was using Gentoo :stuck_out_tongue:), but okay.

**Comment by paul-jewell** [comment]
Maybe the cry of an overworked Gentoo maintainer who doesn't actually use or need the git version of rust-analyzer.  To be honest, I feel that Gentoo is struggling a bit from the workload of staying current with the available pool of developers. I think having proxy-maintainers and the guru repository are approaches to try and increase the currency and availability of packages without recruiting more developers, but that is (in my opinion) a temporary sticking plaster rather than a solution. In my own experience, over the years I have raised several bug reports, together with solutions, and not had any response from the responsible developer. I have two very simple pull requests outstanding at the moment from before Christmas, and seemingly no progress on merging them.

Don't get me wrong - I love Gentoo, and have been a user for more than 20 years. Recently though, I have started to work with NixOS, and have a working install on my laptop. Depending how I get on with it, I can see me migrating all my machines to NixOS :).

Regarding rust-analyzer, and my opinion as a Gentoo user - since I am quite new to rust, it isn't an issue for me at the moment. If in the future I am still on Gentoo and need an up to date install, I will do what I have done with a number of other packages - roll my own ebuild and install it in a local repo!

**Pull request merged**
