### PR TITLE
For toolchain binaries use the full path found in $PATH

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/16754

### CODE REVIEW

**Comment by Veykril** [comment]
@MabezDev this reverts your recent PR, but if I understood the issue you had correctly, my changes in here should not break your workflow again (we now invoke the full path found in $PATH instead of just the binary name if we find a working path in $PATH).

**Comment by MabezDev** [comment]
Unfortunately, this does break my workflow. I checked out this PR and installed locally, replacing my binary which contained my original PR.

```
2024-03-05T13:29:59.280330Z ERROR rust_analyzer::main_loop: FetchBuildDataError:
error: package `block-device-adapters v0.1.0 (/home/mabez/development/rust/embedded/util/embedded-fatfs/block-device-adapters)` cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.74.1
```

It's still trying to use my system Rust, and not the rustup installation.

**Comment by Veykril** [comment]
That's odd, you said " My `$PATH` has `$HOME/.cargo/bin` before `/usr/bin`." in your reported issue before, so this should pick that up. Do you have the `RUSTC` env var set for some reason?

**Comment by Veykril** [comment]
Oh wait, you literally have `$HOME/.cargo/bin` in your path I assume? Is that allowed ? If yes then the logic here won't resolve env vars in there so that would explain the issue

**Comment by MabezDev** [comment]
So I added the source to `.zprofile` and it started working :shrug:. This is odd because it's already in my `.zshenv` which I thought was _always_ sourced, but I guess maybe not? Anyways, this change LGTM now.

**Comment by davidbarsky** [comment]
i'll try this with a buck2-built sysroot once [some issues at work](https://www.theverge.com/2024/3/5/24091207/meta-outage-facebook-instagram-threads-down-signed-out) are resolved.

**Comment by Veykril** [comment]
Does this work?
@bors delegate=davidbarsky

**Comment by Veykril** [comment]
it does!

**Comment by davidbarsky** [comment]
Sorry, am a little sick, so I was out of commission yesterday! A buck2-build sysroot is still successfully indexed with these changes. Thanks for waiting to let me check that.

@bors r=@Veykril

**Pull request merged**
