### PR TITLE
internal: Downgrade actions/checkout in release workflow

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
CC @LucasFA better me than you https://github.com/rust-lang/rust-analyzer/actions/runs/7952745134/job/21714107181 :-).

**Comment by LucasFA** [comment]
My bad, sorry about that. Didn't realise Node 18+ versions weren't compatible with Ubuntu 18.04 https://github.com/actions/checkout/issues/1442#issuecomment-1697949642

Thanks for the rescue 😅

**Comment by lnicola** [comment]
Also https://github.com/rust-lang/rust-analyzer/pull/16599.

**Comment by lnicola** [comment]
And #16600. You did warn me, though.

**Comment by LucasFA** [comment]
I see it's working again from the latest run: https://github.com/rust-lang/rust-analyzer/actions/runs/7956144210

I wasn't expecting several breakages - again, thanks for the rescue and sorry about generating extra work. I'll take this as a lesson on changing CD immediately before a release day, and on system compatibility, I suppose.

**Comment by lnicola** [comment]
No worries, part of the breakage was mine anyway :grinning:.

**Pull request merged**
