### PR TITLE
Render size, align and offset hover values in hex

### PR DESCRIPTION
**Pull request by Veykril**
Arguably, these values are usually almost always viewed in hex format so I think we should do the same here

### CODE REVIEW

**Comment by Veykril** [comment]
We could make this configurable if really desired, but I'll merge this for now.
@bors r+

**Comment by lnicola** [comment]
Bit be nice to only do this for numbers >= 16 or so, but doesn't matter too much.

**Comment by novacrazy** [comment]
This is very annoying. Please make it a toggle. A struct being 0x1B0 bytes in size is meaningless.

**Comment by lnicola** [comment]
Tracked in #14918.

**Comment by lnicola** [comment]
@gabe-lee that was actually added in #14929.

**Pull request merged**
