### PR TITLE
Expand proc-macros in workspace root, not package root

### PR DESCRIPTION
**Pull request by Veykril**
Should fix https://github.com/rust-lang/rust-analyzer/issues/17748. The approach is generally not perfect though as rust-project.json projects don't benefit from this (still, nothing changes in that regard)

### CODE REVIEW

**Comment by max-sixty** [comment]
Thank you!

**Comment by max-sixty** [comment]
@Veykril thanks for giving this a go.

Unfortunately I don't think it solved the problem. The repro in #17748 still fails. I'm on `v0.3.2096` which contains this commit.

If I augment this to the repro, on nightly rustc:

```
#[proc_macro]
pub fn test_each_file(_input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    dbg!(env!("CARGO_MANIFEST_DIR"));
    dbg!(std::env::var("CARGO_RUSTC_CURRENT_DIR"));

    let current_dir = dbg!(std::env::current_dir().unwrap());
    assert!(dbg!(Path::new("./ROOT.txt")).is_file());
    assert!(dbg!(Path::new("./ROOT.txt").canonicalize().unwrap()).is_file());
    proc_macro::TokenStream::new()
}
```

...then `cargo build` shows that it's using the workspace root as cwd:

```
[test_macro/src/lib.rs:5:5] env!("CARGO_MANIFEST_DIR") = "/Users/maximilian/workspace/test-each-file/test_macro"
[test_macro/src/lib.rs:6:5] std::env::var("CARGO_RUSTC_CURRENT_DIR") = Ok(
    "/Users/maximilian/workspace/test-each-file",
)
[test_macro/src/lib.rs:8:23] std::env::current_dir().unwrap() = "/Users/maximilian/workspace/test-each-file"
[test_macro/src/lib.rs:9:13] Path::new("./ROOT.txt").canonicalize().unwrap() = "/Users/maximilian/workspace/test-each-file/ROOT.txt"
[test_macro/src/lib.rs:10:13] Path::new("./ROOT.txt") = "./ROOT.txt"
```

But Rust Analyzer Language Server log doesn't find the newly added `CARGO_RUSTC_CURRENT_DIR` var and is still using the crate root:

```
[test_macro/src/lib.rs:5:5] env!("CARGO_MANIFEST_DIR") = "/Users/maximilian/workspace/test-each-file/test_macro"
[test_macro/src/lib.rs:6:5] std::env::var("CARGO_RUSTC_CURRENT_DIR") = Err(
    NotPresent,
)
[test_macro/src/lib.rs:8:23] std::env::current_dir().unwrap() = "/Users/maximilian/workspace/test-each-file/test_src"
```

(if you don't see this, I'll open a new issue, hope that's reasonable, thank you!)

**Comment by Veykril** [comment]
Oh I see the issue, the env var is set for the proc-macro crate, but we need to it to be set for the calling crate

**Pull request merged**
