### PR TITLE
comment out disabled code

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
What's the benefit of doing this? If the code is commented out it won't be type-checked

**Comment by danieleades** [comment]
> What's the benefit of doing this? If the code is commented out it won't be type-checked

see https://github.com/rust-lang/rust-analyzer/pull/13863#issuecomment-1367881578

it's a clippy error, which causes clippy to error out early, potentially suppressing other more useful lints

**Comment by Veykril** [comment]
I think we can surpress the clippy lint on this specific code block (commenting out, as Jonas said, is not ideal) given that I do would like to see us use some clippy lints in the future once you can select things on a project wide scale better. And this lint isn't wrong per se.

**Comment by lnicola** [comment]
We have a test that checks for `allow(clippy` though.

**Comment by Veykril** [comment]
Then we might want to remove that one I'd say 😅

**Comment by danieleades** [comment]
@Veykril this is marked as "waiting on author", but I'm not sure what the action is on me here

**Comment by lnicola** [comment]
Can you add an allow attribute instead of commenting out the code, then remove the failing test?

**Comment by danieleades** [comment]
> Can you add an allow attribute instead of commenting out the code, then remove the failing test?

done

**Pull request merged**
