### PR TITLE
Move manual to mdBook

### LINKED ISSUE #9504: Manual needs to be more helpful, friendly, and better organized
rust-analyzer manual is pretty long: https://rust-analyzer.github.io/manual.html

It's useful as a reference, but is quite intimidating if you want to learn the tool. We should improve this, both in terms of logical organization, and in terms of HTML&CSS rendering. I am not experienced with it, so help would be much appreciated. 

I think ideally the manual shows a short pit of success, while giving the links to in-depth reference material. Here's a structure I have in mind:

First is quick start, which suggests choosing an editor (VS Code, Vim, Emacs). For a specific editor, we have a single blessed setup. After the setup, we have a short section show-casing the most important features (worksapce symbol, go to definiton, extend selection, running tests, triggering assists). This should be duplicated for editor, and serves two purposes -- teaches about the features and allows the new user to verify if the stuff is working. Aftre quick start and show case, we show how to configure rust-analyzer in the specific editor. After that, we show alterntive setups

After per-editor quick start, we probably want to re-create show case, with the emprasis on how it looks and why it is useful, rather than on which shourtcur do you use to trigger this. 

After universal show-case, we should have an index of features, which leads to specific pages for diagnostics, assists, etc.

After that, we should have troubleshooting and other stuff. 

As I've said, I am not an expert at this: if you think you see a better way to do this, feel free to suggest. The source for manual lives here: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user.

It is render to a web document here: https://github.com/rust-analyzer/rust-analyzer.github.io

The code to move the manual from the first place to the second place is here: https://github.com/rust-analyzer/rust-analyzer/blob/91bfa4b154a9776a57f25071f03e68d4f9f5ef35/xtask/src/release.rs#L25-L50

### PR DESCRIPTION
**Pull request by joshrotenberg**
I made a mess of this last time around. Here is another try, fortunately with lots of hindsight. 

Fixes #9504.

Manually deployed to: http://joshrotenberg.com/rust-analyzer/index.html 

This is a work in progress. Here are the current steps, with probably more to come.

- [X] - Convert `docs/user/manual.adoc` to markdown.

I did this with [pandoc](https://pandoc.org) using something similar to this [blog post](https://karinavarela.me/2020/05/06/converting-asciidoc-to-markdown/). For the static content,
this worked really well. 

- [X] - Create a base [mdbook](https://github.com/rust-lang/mdBook) setup. 

I used `mdbook init` and then reused my previous `book.toml` and `SUMMARY.md`. 

- [X] - Sweep through the generated markdown for lints, images, style, etc.

I moved each section according to the current manual to match the mdbook structure, and in the process fixed some minor issues, restructured headings, brought in the images, lint, etc. 

- [X] - Move the developer guide to the book.

This isn't absolutely necessary but it does consolidate the docs in one place, and since `docs/dev` is already markdown it was easy. I did go through and do some minor linting/markdown style but for the most part the `Contributing` section of the book is the same as `docs/dev`.
 
- [X] - Convert generated docs from adoc to markdown.

This is a big chunk of the work, obviously, and is a fairly atomic step which makes everything above a little bit more difficult: the current manual and the new manual can't really coexist, at least not fully functional (or without some kind of interim conversion). 

- [X] - Remove old docs.

Just a matter of deciding where the new manual should live (top level manual directory? `docs/user`? `docs/manual`?). I've got `docs/manual` for now.

Edit: had to change a path in a source file as well.

- [X] - Update release for mdbook files.

Right now the adoc files are handled explicitly in the task: https://github.com/rust-lang/rust-analyzer/blob/7c8ae35648099189e550c873c0dae3a4ca6c50a9/xtask/src/release.rs#L49

- [ ] - Figure out deployment.

I'm still a little confused about this, need to dig around again. 

- [ ] - Solve workflow failures.

- [X] - Deploy current state on fork.

See <http://joshrotenberg.com/rust-analyzer/index.html>. Will be updated periodically.

Screenshots

Introduction:

Screenshot 2023-06-26 at 4 43 03 PM

Features:

Screenshot 2023-06-28 at 12 03 38 PM

Assists:

Screenshot 2023-06-28 at 12 04 36 PM

Diagnostics:

Screenshot 2023-06-28 at 12 06 36 PM

### CODE REVIEW

**Comment by Veykril** [comment]
This looks great!

**Comment by Veykril** [comment]
oh before you continue to build on the merge commits, can you try and get rid of those. We don't really want to have merge commits aside from bors in the tree (Ill also be gone for the rest of the month so if you want a review from me in that time span you'll have to wait)

**Comment by Wilfred** [comment]
This looks really good! Anything I can do to help?

**Comment by joshrotenberg** [comment]
> This looks really good! Anything I can do to help?

I put it down for a bit since @Veykril was off, and then I messed something up with the commits and haven't had a chance to fix it yet. For the most part things were looking pretty good. Once I get it back in shape I guess making any updates to doc changes that have happened recently, and then reviews and decisions around the best way to merge and deploy this. If you have any feedback, though, I'm all ears.

**Comment by joshrotenberg** [comment]
Once again I messed up my branch. Ugh. I'm going to move the work and information over and create a new one and hopefully get this thing taken care of.

**Comment by joshrotenberg** [comment]
Hopefully this is the one! https://github.com/rust-lang/rust-analyzer/pull/15795

@Veykril  @Wilfred would love a review.

**Pull request closed without merging**
