### PR TITLE
Add basic tooltips to adjustment hints

### PR DESCRIPTION
**Pull request by WaffleLapkin**
I'm not sure how to make them look nicer, but it's at least something.

### CODE REVIEW

**Comment by Veykril** [comment]
This will probably need a rebase after https://github.com/rust-lang/rust-analyzer/pull/13946/ is merged. Regarding making it look nicer, tooltips do support markdown (after #13946 there is a corresponding tooltip variant for markdown), so you could tinker with that.

**Comment by WaffleLapkin** [comment]
It was perfect time for this PR wasn't it 😅

**Pull request merged**
