### PR TITLE
minor: fix ide docs link

### PR DESCRIPTION
**Pull request by Veykril**
Let's test if bors listens to me here
bors r+

### CODE REVIEW

**Comment by lnicola** [comment]
Did you mean @bors r+?

**Comment by lnicola** [comment]
:unamused: 

@bors r+

**Comment by Veykril** [comment]
We didnt switch yet afaik

**Comment by Veykril** [comment]
image

**Comment by Veykril** [comment]
bors ping

**Comment by Veykril** [comment]
let's see if we have to fix the tidy test actually or if it just works out 🤞

**Comment by jyn514** [comment]
> 🍰 Target acquired
> 
> 

https://youtu.be/_kPyGvqNn4Y

**Pull request merged**
