### PR TITLE
feat: goto definition on range operators

### LINKED ISSUE #18342: Go to definition on `..`/`..=` should go to the corresponding `Range*` type
As in `1..2` should go to `Range`, `1..` to `RangeExclusive` etc

### PR DESCRIPTION
**Pull request by duncpro**
Closes #18342

### CODE REVIEW

**Review by Veykril — COMMENTED** [review]
(shouldve said that in the issue as a mentoring instruction sorry)
I think we should add a couple new `OperatorClass`es (`OperatorClass::Range(Struct)`, etc) here for the range types https://github.com/rust-analyzer/rust-analyzer/blob/fb832ff2ba338105dda1c8172f89d580cb0a570f/crates/ide-db/src/defs.rs#L548-L554 and populate them here https://github.com/rust-analyzer/rust-analyzer/blob/fb832ff2ba338105dda1c8172f89d580cb0a570f/crates/ide-db/src/defs.rs#L309-L330

WIth that I think the go to def code needs no changes in fact (aside from tests) and this should automatically give us support for ranges in other ide features as well (like hover and stuff)

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Review by 1234Brian — APPROVED** [review]

**Comment by duncpro** [comment]
@Veykril Thank you for helping me along. This was my first real OSS contribution.

**Comment by Veykril** [comment]
Ah, if you want there is a follow up task. We can do the same for patterns I just realized, not just expressions since there are also range patterns :)

**Comment by duncpro** [comment]
I'm down. I'll open an issue for it right now

**Pull request merged**
