### PR TITLE
Substitute some VSCode variables in the VSCode client

### PR DESCRIPTION
**Pull request by Veykril**
cc https://github.com/rust-lang/rust-analyzer/issues/13405

### CODE REVIEW

**Comment by davidbarsky** [comment]
Oh, thanks for doing this! I was gonna write it anyways, but it's great to be able to start resolving this issue sooner than I expected :)

**Comment by Veykril** [comment]
I was rewriting things anyways for https://github.com/rust-lang/rust-analyzer/pull/13426 so I went and took a look at this while I was at it :)

**Comment by ashb** [comment]
:+1: Thanks, for this -- I just switched to the nightly/pre-release VsCode extension and it fixed my problem (of specifying `VIRUTAL_ENV` relative to `workspaceFolder` for a pyo3 project)!

**Pull request merged**
