### PR TITLE
fix: Disable invalid cast diagnostics for casts like `&T as &dyn Trait`

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Hope this might suppress false positive diagnostics like #18047

### CODE REVIEW

**Comment by ShoyuVanilla** [comment]
So many typos 😅 Will fix and squash tomorrow

**Comment by HKalbasi** [comment]
Shouldn't we also suppress it for `Box<dyn T>` as well?

**Comment by ShoyuVanilla** [comment]
> Shouldn't we also suppress it for `Box<dyn T>` as well?

Oh, you're right. I neglected it

**Comment by ShoyuVanilla** [comment]
It seems that I misdiagnosed the cause of the issue. The test I added works fine without any modification to the logic if I just add `minicore: builtin_impls`

**Comment by ShoyuVanilla** [comment]
https://github.com/rust-lang/rust-analyzer/issues/18047#issuecomment-2333017248

**Pull request closed without merging**
