### PR TITLE
feat: Map tokens from `include!` expansion to the included file

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes https://github.com/rust-lang/rust-analyzer/issues/3767

### CODE REVIEW

**Comment by Veykril** [comment]
@bors r+
That was a lot simpler than I would've expected it to be

**Comment by davidbarsky** [comment]
just have to say: this is _awesome_ and i'm really thankful you managed to make this change.

**Comment by NickLarsenNZ** [comment]
I'm running the nightly version (I believe), and I am getting the following error when trying to jump to the code:

```
thread 'Worker' panicked at 'Bad offset: range 0..319 offset 153598', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rowan-0.15.11/src/cursor.rs:751:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::SyntaxNode::token_at_offset
   3: ide::goto_implementation::goto_implementation
   4: std::panicking::try
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   7: rust_analyzer::handlers::handle_hover
   8: std::panicking::try
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 22:24:15] Request textDocument/hover failed.
  Message: request handler panicked: Bad offset: range 0..319 offset 153598
  Code: -32603 
```

This happens when I hover over [`dapr_v1::TopicEventResponse`](https://github.com/dapr/rust-sdk/blob/022817e9bfc24c937b69f320d8067415f73c15f3/src/appcallback.rs#L24)

And when I CMD+Click to follow it anyway, it jumps to the [end of the file](https://github.com/dapr/rust-sdk/blob/ef8ca517b75929032af7eb84adb8e9471798042b/src/dapr.rs#L14-L15) where the `tonic::include_proto!` is called.

I have tried with the following setting in vscode too (to no avail):

```json
{
    "rust-analyzer.cargo.buildScripts.enable": true,
}
```

I'm unsure if the [`build.rs`](https://github.com/dapr/rust-sdk/blob/5016f61f7e917d2b7a4eeeaef2655bba4a602e3d/build.rs) is of any significance in this issue.

**Comment by Veykril** [comment]
Ah I think I can guess the problem here, the upmapping code that calls `ExpansionInfo::map_token_up` probably assumes the upmapped token to come from the file that contains the macro call, so when it then recursively tries to upmap again this assumption not being correct breaks things due to the include being done in a macro expansion.

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/232407988-7c526795-78b7-4802-90c1-0a9e200f7d95.mp4

**Comment by zhouzq-thu** [comment]
With opencv-rust crate, goto definition works fine for the functions like `dnn::get_available_backends`, but can't goto the right place for the traits (member functions) like `model.set_preferable_backend`. Maybe the `rust-analyzer` still has some bugs.

**Comment by lnicola** [comment]
> Maybe the rust-analyzer still has some bugs.

Yeah, about 1233 open ones :grimacing:.

There are some known situations where we pick up the wrong trait member. If you could minimize it (outside of `opencv-rust`), that would be nice, but I don't think it's related to the handling of `include!`.

**Comment by TroyKomodo** [comment]
How do we enable this feature?
It does not seem to work with tonic.

**Comment by lnicola** [comment]
@TroyKomodo Go to definition should work, as seen in the recording above. If it doesn't work for you and it's not #14611, please file a new issue.

**Comment by TroyKomodo** [comment]
@lnicola Does it expected with submacros?

```rs
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"))
}
```

**Comment by lnicola** [comment]
That's what the gdal-sys crate does: https://github.com/georust/gdal/blob/master/gdal-sys/src/lib.rs.

**Pull request merged**
