### PR TITLE
style: rename crates to kebab-case

### PR DESCRIPTION
**Pull request by randomicon00**
Ref: #12102 
I updated all the folders names as well as the crates names in each `Cargo.toml` to use kebab-case.

This is my first ra PR. In case I missed something, I am ready/available to fix it until it is ready to merge.

Thank you.

### CODE REVIEW

**Comment by lnicola** [comment]
Can you rebase? It seems there's a conflict on one file.

**Review by lnicola — APPROVED** [review]

**Comment by randomicon00** [comment]
Yes, I can. My current branch doesn't include the latest 4 changes.

**Comment by jonas-schievink** [comment]
Looks like you rebased master onto your branch, not your branch onto master

**Comment by lnicola** [comment]
@randomicon00 I think there's still a failing test that checks that a generated file is up to date. Do you need help with this?

**Comment by randomicon00** [comment]
@randomicon00 I will have a look at it tonight or tomorrow morning and let you know.

**Comment by lnicola** [comment]
Looks good. If it's not too much of a hassle, can you do a final squash to get rid of the swapfile?

@bors delegate+

**Comment by randomicon00** [comment]
As much as the task is trivial, as much as branch conflits seem to keep rolling!  
@lnicola what would be, please, the best approach to resolve these conflicts?

**Comment by lnicola** [comment]
I would squash, then rebase and fix the conflicts. Then merge it without waiting for a review (leave a comment with @ bors r=lnicola).

**Comment by randomicon00** [comment]
all tests are passing. @bors r=lnicola

**Comment by Veykril** [comment]
Good thing we *only* had ~20 open PRs and not more 😅

**Comment by lnicola** [comment]
Nope, looks like you didn't actually squash the changes :smile: 

image

**Comment by randomicon00** [comment]
Good morning! I squased the last 6 commits.

**Comment by pksunkara** [comment]
This broke the publish action as you can see by https://github.com/rust-lang/rust-analyzer/runs/6524727008?check_suite_focus=true#step:5:223. cc @jonas-schievink 

I am not sure why this change was made.

**Comment by Veykril** [comment]
This change was made for consistency, we had some crates using kebab-case and some using snake_case before.

**Comment by pksunkara** [comment]
So, how do we fix the old crates being named with `_`? Crates.io is not allowing us to publish with `-`, I think.

**Pull request merged**
