### PR TITLE
internal: store indeterminate imports alongside unresolved ones

### PR DESCRIPTION
**Pull request by rosefromthedead**
Seems to give some speedups, especially in diesel inference: 298s -> 272s on my machine.

### CODE REVIEW

**Comment by rosefromthedead** [comment]
Err, maybe it doesn't make sense for this to affect inference. I'm new to the perf infrastructure around here, is there a recommended way of measuring the difference?

**Comment by lnicola** [comment]
`analysis-stats` is the way to measure the difference. I didn't test on `diesel`, but on `self` it doesn't seem to have any effect on the performance _or_ the accuracy of type inference (which is a good thing).

**Comment by rosefromthedead** [comment]
Yeah, my measurements had a lot more noise than I thought. I'm not sure this PR makes a difference to anything now.

**Comment by Veykril** [comment]
I also don't see where this would really save anything, we are getting rid of the `extend` in the `collect` but that's not a hot path. Though the `retain_mut` is probably a bit better in terms of allocation saving

**Comment by Veykril** [comment]
Closing as there seems to be no benefit from doing this

**Pull request closed without merging**
