### PR TITLE
improve compile time a bit

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+
🤖

**Comment by kjeremy** [comment]
Just out of curiosity by how much did it help?

**Comment by matklad** [comment]
I haven't measured it. The `improve comile time` refers only to the last commit, whch changes impl to dyn in one place. I really should improve my auto-bors-r+ script to require a message if i am sending more than one commit....

**Comment by bjorn3** [comment]
> I really should improve my auto-bors-r+ script to require a message if i am sending more than one commit....

You are using a bot to tell a bot to merge your PR's?

**Comment by matklad** [comment]
Not a bot, just a shell function: https://github.com/matklad/config/blob/master/fish/functions/gbors.fish

For now :)

**Pull request merged**
