### PR TITLE
fix: copied proc-macros not being cleaned up on exit

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Review by Veykril — COMMENTED** [review]
Can anyone inform me about what's unsafe about https://docs.rs/memmap/latest/memmap/struct.Mmap.html#method.map, given the docs don't state it?

**Comment by lnicola** [comment]
Is that the right crate? I suspect it's because another process can truncate or change the file while you're reading from it. See also https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html#safety.

**Comment by Veykril** [comment]
Ah okay, so I was right. That means technically our usages are unsound ...

**Comment by lnicola** [comment]
I'm not to worried about the memory maps causing a crash. I think there's a very small window when we have the library mapped, but not loaded.

**Pull request merged**
