### PR TITLE
Add upper limit for the number of completion items

### PR DESCRIPTION
**Pull request by tech-ticks**
I'm using rust-analyzer on a project with a `bindgen`'d file that contains a large number of functions and structs. Code completion on this project took extremely long due to the large number of items that are rendered and sent to the IDE.

This PR drastically improves performance in cases where lots of completion results are found by adding an upper limit to the list of completion items. Comparison on a (real-world) extreme case with over 200,000 items in one crate:

# Before
```
13557ms - handle_completion
       18ms - CompletionContext::new
           14ms - CompletionContext::expand_and_fill
                0   - Semantics::analyze_impl (1 calls)
                0   - SourceBinder::to_module_def (4 calls)
                0   - crate_def_map:wait (2 calls)
               14ms - ???
            0   - Semantics::analyze_impl (1 calls)
            0   - crate_def_map:wait (2 calls)
            1ms - descend_into_macros (1 calls)
    11750ms - complete_expr_path
         1226ms - render_resolution
             1226ms - render_fn
                 1226ms - lang_item_query
                     1222ms - crate_lang_items_query
                            6ms - collect_lang_item
                           18ms - collect_lang_item
                            9ms - collect_lang_item
                         1155ms - collect_lang_item (344777 calls)
                            0   - crate_def_map:wait (1 calls)
                           31ms - ???
                    0   - crate_def_map:wait (6 calls)
           11ms - render_resolution
               11ms - render_fn
                    0   - crate_def_map:wait (6 calls)
                   11ms - ???
           22ms - PerNs::filter_visibility (235244 calls)
          160ms - crate_def_map:wait (235245 calls)
          781ms - generic_params_query (133796 calls)
           88ms - item::Builder::build (235244 calls)
         6772ms - render_resolution (235242 calls)
         2687ms - ???
        0   - Semantics::analyze_impl (1 calls)
        0   - crate_def_map:wait (2 calls)
     1788ms - ???
```

In practise, it takes much longer for the code completion result to show up in the IDE since processing such a large list puts quite a burden on VS code as well (and/or it's an IO bottleneck during communication between the extension and rust-analyzer).

# After
```
1988ms - handle_completion
       18ms - CompletionContext::new
           15ms - CompletionContext::expand_and_fill
                0   - Semantics::analyze_impl (1 calls)
                0   - SourceBinder::to_module_def (4 calls)
                0   - crate_def_map:wait (2 calls)
               15ms - ???
            0   - Semantics::analyze_impl (1 calls)
            0   - crate_def_map:wait (2 calls)
            0   - descend_into_macros (1 calls)
     1953ms - complete_expr_path
         1307ms - render_resolution
             1307ms - render_fn
                 1306ms - lang_item_query
                     1301ms - crate_lang_items_query
                            8ms - collect_lang_item
                           18ms - collect_lang_item
                           18ms - collect_lang_item
                         1222ms - collect_lang_item (344777 calls)
                            0   - crate_def_map:wait (1 calls)
                           34ms - ???
                        5ms - ???
                    0   - crate_def_map:wait (7 calls)
           27ms - PerNs::filter_visibility (235244 calls)
            1ms - crate_def_map:wait (2049 calls)
            7ms - generic_params_query (1681 calls)
            0   - item::Builder::build (2048 calls)
           64ms - render_resolution (2047 calls)
          544ms - ???
        0   - Semantics::analyze_impl (1 calls)
        0   - crate_def_map:wait (2 calls)
       16ms - ???
```
The time spent in `render_resolution` is greatly reduced and results show up in the IDE right after the trace is printed to the console. The compromise here is that only 2048 items are displayed at most (but the relevant ones are likely at the top of the list).

### CODE REVIEW

**Comment by Veykril** [comment]
I'm a bit confused here, are you actually `*` (glob) importing the bindgen file into your files? Or are you editing inside the bindgen file? Otherwise you shouldn't have these problems, and doing either of that sounds like a bad choice imo. I'd rather not impose a limit on completions generations here personally (also because this change is rather invasive, given we have to touch up every "add" function here)

**Comment by tech-ticks** [comment]
> I'm a bit confused here, are you actually `*` (glob) importing the bindgen file into your files? Or are you editing inside the bindgen file? Otherwise you shouldn't have these problems, and doing either of that sounds like a bad choice imo. I'd rather not impose a limit on completions generations here personally (also because this change is rather invasive, given we have to touch up every "add" function here)

@Veykril Sorry, I should have gone into more detail in the description... It's unfortunately not only an issue with glob imports. rust-analyzer also hangs when you type `crate_name::...`, which is unfortunate because the actual query behind the autocomplete still executes in a reasonable time, it's just the conversion in `render_resolution` and I/O or processing in VS Code that take way too long.

The major issue here is that even if you type e.g. `crate_name::prefix_`, rust-analyzer will still render and send all autocomplete items in `crate_name` without any filtering and then the fuzzy string matching is done by VS Code on the entire data set. Performance is more acceptable on a lower scale here, but completely breaks with a lot of items. I didn't notice that rust-analyzer was lacking pre-filtering here, so relevant completion items are actually missing in the current state of the PR. I wanted to tackle that too (and already have a prototype implementation that is a lot faster with this project), but didn't have time to finish it yet.

I do realize that autocompletion for a crate with 200,000 items is an extremely ridiculous usecase, but I think that at least filtering items on the rust-analyzer side instead of relying on VS Code would yield performance improvements in less extreme cases as well since it would save time on processing in `render_resolution`, serializing a large chunk of JSON data and processing it in VS Code. Limiting the total number of autocomplete items seemed like a good idea to me as well to save on some resources in cases where users probably won't look through thousands of suggestions, but there are of course some drawbacks as well as you've mentioned. Either way, the lack of pre-filtering items based on their name seems to be the main culprit for more common use cases here. Feel free to close this PR, I'd either way like to follow up on filtering sometime if you agree that it would be useful.

**Comment by flodiebold** [comment]
Maybe we should instead just limit the number of returned completions on the LSP layer?

**Comment by flodiebold** [comment]
Also, maybe a possible workaround would be to mark the bindgen-generated items `#[doc(hidden)]`? I can't imagine you can generate a useful documentation file with 200000 items either...

**Comment by matklad** [comment]
Couple of thoughts: 

* Yes, we should limit this server-side. That's a general rule for I think any LSP request -- there's never a need to return more items which can be displayed on a single screen
* We should limit this in the LSP layer **after** we sorted completions in the order of relevance 
* which means that https://github.com/rust-lang/rust-analyzer/issues/7935 is sadly a pre-requisite 


What we can do immediately though, is to make this configurable, and have infinite limit by default.

**Comment by matklad** [comment]
Partial mentoring instructions for lsp-layer limiting: https://users.rust-lang.org/t/how-many-symbols-can-rust-analyzer-autocomplete-in-practice/81400/5?u=matklad

**Comment by tech-ticks** [comment]
> Couple of thoughts:
> 
> * Yes, we should limit this server-side. That's a general rule for I think any LSP request -- there's never a need to return more items which can be displayed on a single screen
> * We should limit this in the LSP layer **after** we sorted completions in the order of relevance
> * which means that [Implement server-side completion sorting and filtering #7935](https://github.com/rust-lang/rust-analyzer/issues/7935) is sadly a pre-requisite

Yeah, I've already experimented with server-side filtering a bit (only with non-fuzzy matching) but I'm unfortunately a bit low on time right now. Maybe I'll have resources to look into it again in the next few weeks but I can't promise that.

> What we can do immediately though, is to make this configurable, and have infinite limit by default.

I could update this PR to make the limit configurable. I'm not sure if it actually makes sense though since it would exclude relevant items in the current state, which isn't what anyone would want, unless if it would be used in conjunction with the server-side filtering later.

**Pull request closed without merging**
