### PR TITLE
fix #11986 Aliases break resolution of qualified variants in patterns

### LINKED ISSUE #11986: Aliases break resolution of qualified variants in patterns
**rust-analyzer version**:  rust-analyzer version: faaec86ff 2022-04-12 nightly

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

https://github.com/rust-lang/rust-analyzer/blob/13f36e7397065bc77747a4a28f8266f9fe472f8a/crates/hir/src/lib.rs#L3159-L3164
`hir_ty::WhereClause::Implemented` is unresolved:
q16

Minimized:
```rust
mod m {
    pub enum Enum {
        Foo(u8),
    }
    pub type Alias = Enum;
}
fn f() {
    let e = m::Alias::Foo(0);
    let m::Alias::Foo(x) = &e;
}
```

### PR DESCRIPTION
**Pull request by bitgaoshu**

### CODE REVIEW

**Comment by flodiebold** [comment]
Makes sense, but it seems it doesn't quite compile, maybe due to some last-minute change?

**Comment by bitgaoshu** [comment]
yes, fixed

**Comment by bitgaoshu** [comment]
@flodiebold can review this PR?

**Comment by flodiebold** [comment]
Sorry, yeah!

@bors r+

**Comment by bitgaoshu** [comment]
thanks!

**Pull request merged**
