### PR TITLE
fix: don't trigger `unwrap result return type` when inside trait impls

### LINKED ISSUE #13560: "Unwrap `Result` return type" shouldn't trigger in trait impls
```rust
trait Tr {
    fn f() -> Result<(), ()>;
}

impl Tr for () {
    fn f() -> $0Result<(), ()> {
        todo!()
    }
}
```

This offers the "Unwrap `Result` return type", which removes the return type here, but this is wrong in a trait impl if the trait isn't also modified (which requires fixing up every impl of it).

### PR DESCRIPTION
**Pull request by dbofmmbt**
Closes #13560

@jonas-schievink do you think it's okay to just stop triggering the action for the trait impl case?

I noticed that another assist was mentioned in the issue. I could apply this treatment there too.

I'll appreciate any suggestions.

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Hm, actually re-reading the issue, it's a good general question that was raised there. I feel like we should probably recognize doing signature changes in trait impls/defs, and apply the changes to all other impls and the trait def at once?

**Comment by dbofmmbt** [comment]
If we go for the path of applying signature changes where needed, should we care if the change breaks compatibility with something else?  

E.g. another crate may depend on a trait that was changed.

Anyway, I think the way you proposed would be more interesting. It would be a good oportunity for me to be more familiar with RA, since it looks more complex :)

**Comment by Veykril** [comment]
We should apply the changes to the entire workspace, but if the corresponding trait is not defined in a workspace crate we should not trigger the assist at all.

**Comment by Veykril** [comment]
Hmm, that might be the better option for now.

**Comment by lowr** [comment]
As an implementation hint: I think you should check where the cursor is at not syntactically but semantically - that is, using HIR instead of AST. Even if the cursor is *inside* a trait impl, we want to provide the assist if it's *at* inner item:

```rust
impl Trait for Struct {
    fn foo() -> /*$0*/Result<(), ()> { // we don't want the assist here
        fn bar() -> /*$0*/Result<(), ()> { // but it's reasonable to provide the assist here
            todo!()
        }

        todo!()
    }
}
```

**Comment by Veykril** [comment]
Closing as its inactive, if you get back to this feel free to re-open

**Pull request closed without merging**
