### PR TITLE
Deduplicate tuple indices for completion

### PR DESCRIPTION
**Pull request by lowr**
Follow-up to #15026

A tuple struct may dereference to a primitive tuple (though unusual, which is why I previously overlooked this case). We should not show the same tuple index in completion in such cases.

Deduplication of indices among multiple tuple structs is already handled in the previous PR.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

**Comment by lowr** [comment]
> thread 'syntax_highlighting::tests::syntax_highlighting_not_quadratic' panicked at 'Doesn't look linear!'

@bors retry

**Pull request merged**
