### PR TITLE
internal: Bump deps pt. 1

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Review by davidbarsky — COMMENTED** [review]
not that i'm a meaningful approver (beyond, I suppose, the `tracing`-related stuff), but lgtm :)

**Comment by lnicola** [comment]
I was just asking you if you'd mind a PR to bump your `tracing-log` dependency to 0.2.

**Comment by lnicola** [comment]
Thanks for the quick release, @davidbarsky!

r? @Veykril this isn't complete, but it might bit rot until I take it up again.

We drop `atty`, `hermit-abi` (probably unused), `overload` (from `tracing-log`), while gaining another `itertools`, which needs to be bumped in `chalk`.

**Review by Veykril — APPROVED** [review]

**Pull request merged**
