### PR TITLE
Avoid double text edits when renaming mod declaration

### PR DESCRIPTION
**Pull request by Veykril**
Closes https://github.com/rust-analyzer/rust-analyzer/issues/7916

See https://github.com/microsoft/vscode-languageserver-node/issues/752 for context

### CODE REVIEW

**Comment by matklad** [comment]
Hm, it still feels that something should break loudly here. 

Essentially, we have two conflicting edits, and the client should refuse to apply them. Are we threading text document version correctly? I think what should happen is that the server produces two edits with the same document version, and the client should fail when applying the second one.

**Comment by matklad** [comment]
but yeah, even if the client errors instead of inventing non-existing edit, there's still an error. And yeah, I don't see a better soulution here. So I think, in the handlers layer, if `rename`  returns file edits and the client supports will-rename, we should drop other edits, and hope that will_reanme does fixup.

**Comment by Veykril** [comment]
Whoops I messed my commit up

**Comment by Veykril** [comment]
Ye this is a lot better, I keep forgetting that ide is meant as the ideal client for some reason.

About the document versioning, from the looks of a trace the version seems to change after the `WillRenameFiles` Response https://gist.github.com/Veykril/82356a08971eee767ebb62078bfdd259

**Pull request merged**
