### PR TITLE
minor: Bump a couple of deps

### PR DESCRIPTION
**Pull request by lnicola**
Only a couple because I didn't yet try to untangle the `windows-sys` / `syn 2.0`.

### CODE REVIEW

**Comment by Veykril** [comment]
I wanted to give the ecosystem a bit of time to update to syn2, that was the main reason for pinning. Though I really don't want syn to be duplicated, it is already way too heavy as is 😩

**Comment by lnicola** [comment]
I might do another pass in the next couple of days. This pulls in a second `bitflags`, but it will probably take a while for most crates to upgrade. With `syn` I think we're blocked on `tracing-attributes` (already merged, not released) and `arbitrary` (same, but maybe less active).

**Comment by davidbarsky** [comment]
> With syn I think we're blocked on tracing-attributes (already merged, not released)

I'll try to get a release out this week.

**Comment by Veykril** [comment]
Chalk also upgraded already

**Comment by lnicola** [comment]
No worries, salsa will take much longer to upgrade.

**Comment by lnicola** [comment]
Yeah, but it's still pulling in both: https://github.com/rust-lang/chalk/pull/793#issuecomment-1487935948.

**Comment by Veykril** [comment]
Oh no, salsa depends on it as well right... That's a problem.

**Pull request merged**
