### PR TITLE
Use anonymous lifetime where possible

### PR DESCRIPTION
**Pull request by lowr**
Because anonymous lifetimes are *super* cool.

More seriously, I believe anonymous lifetimes, especially those in impl headers, reduce cognitive load to a certain extent because they usually signify that they are not relevant in the signature of the methods within (or that we can apply the usual lifetime elision rules even if they are relevant).

### CODE REVIEW

**Comment by HKalbasi** [comment]
IIRC there is a clippy lint for that, you can use it to check if any of them missed (in case you already didn't do that).

**Comment by lowr** [comment]
That's what I anticipated, but I couldn't find it. Mind checking it?

**Comment by HKalbasi** [comment]
It is probably this: https://rust-lang.github.io/rust-clippy/master/#/needless_lifetimes

**Comment by lowr** [comment]
So I've rechecked but no lints in https://rust-lang.github.io/rust-clippy/master/#/lifetime got triggered by this code :/ I might as well file an issue for clippy.

```rust
struct S<'a>(&'a i32);
impl<'a> S<'a> {}
```

**Comment by HKalbasi** [comment]
It is reported: https://github.com/rust-lang/rust-clippy/issues/10394

So let's merge this.
@bors r+

**Pull request merged**
