### PR TITLE
fix: let glob imports override other globs' visibility

### LINKED ISSUE #11858: conflict between `use` and `pub use` in crate re-exports
crate `mylib`:
```rust
mod bar {
  pub struct Foo;
}
use bar::*;
pub use bar::*;
```
`main.rs`:
```rust
use mylib::Foo;

pub fn f(_: &Foo) {}
fn main() {
  let foo = mylib::Foo;
  f(&foo); // type mismatch: expected &{unknown}, found &Foo
}
```
Other observations about this example: hovering over the reference to `Foo` in `f` shows that it is not recognized, which is why `&{unknown}` is expected in the type mismatch. `rustc` compiles this without issue. If both glob imports are replaced by imports of `bar::Foo`, then it fails to compile because two `Foo` names are introduced in the scope of `mylib`; if only the private one is replaced by `Foo` then rustc will treat `Foo` as private even though there is a public glob use. (It is not clear whether this behavior is intentional / desirable in rustc: [zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Adding.20private.20imports.20can.20break.20downstream.20crates), rust-lang/rust#95420.)

**rust-analyzer version**: `63c4d6b20 2022-03-30 nightly`

**rustc version**: `rustc 1.61.0-nightly (52b34550a 2022-03-15)`

### LINKED ISSUE #14902: unresolvedReference for trait arrow_array::ArrowPrimitiveType
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) rust-analyzer version: 0.4.1529-standalone (06d02e0a1 2023-05-25)

**rustc version**: (eg. output of `rustc -V`) rustc 1.69.0 (84c898d65 2023-04-16)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`) default settings

image

```rust
use arrow_array::ArrowPrimitiveType;
```

```toml
[dependencies]
arrow-array = "40.0.0" 
```

### PR DESCRIPTION
**Pull request by lowr**
Fixes #11858
Fixes #14902

### CODE REVIEW

**Comment by lowr** [comment]
While I think I did implement the right semantics, it complicates code (especially in that there are now two methods to push resolution to `ItemScope`) and I don't really like it implementation-wise. I'd like to reconsider the implementation a bit.

@rustbot author

**Comment by Veykril** [comment]
Having looked myself at the import resolution code for some other stuff, I wonder if we can rewrite the entire thing in a different way (not speaking of your changes here, haven't looked at them). I don't like how it currently looks, and it also seems to place some stuff into item scope that's only relevant for the import resolution.

**Comment by Veykril** [comment]
Closing due to inactivity

**Comment by Throne3d** [comment]
Thanks for doing this code implementation! I've just rebased it onto the latest version of rust-analyzer, and it solved an issue I was having with arrow_array. Looks like this issue will be fixed in an upcoming version of RA. =)

**Pull request closed without merging**
