### PR TITLE
fix: Fix standard flycheck command not being executed in the workspace it is being invoked for

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/13477

### CODE REVIEW

**Comment by Veykril** [comment]
@lnicola when you do today's release, could you make sure to have this included? (I don't remember if we just publish the last nightly as stable) This issue will bug a lot of people otherwise 😬

**Comment by lnicola** [comment]
Oof, sorry, I missed the ping here :(

**Comment by Veykril** [comment]
No worries, I should've pinged you on zulip for this/I should've kicked off a nightly I suppose :)

**Pull request merged**
