### PR TITLE
feat: Nest Cargo.lock under Cargo.toml in Code

### LINKED ISSUE #13580: Add Cargo file nesting pattern
In VS Code you can add:

`"explorer.fileNesting.patterns": {
        "Cargo.toml": "Cargo.lock"
    },`

In order to collapse .toml and .lock under one file (you can still expand it if you want).

I think this rule you be added by default by rust analyzer plugin.

### PR DESCRIPTION
**Pull request by lnicola**
Closes #13580

### CODE REVIEW

**Comment by lnicola** [comment]
image

image

**Comment by lnicola** [comment]
@bogdanmarinescu do you know if this can be disabled? I tried to set `"explorer.fileNesting.patterns": {}` in my `settings.json` and nothing happened.

Arguably it's a Code problem, but I'm a bit worried that this will annoy a lot of users.

**Comment by bogdanmarinescu** [comment]
Maybe you have `explorer.fileNesting.enabled": true` in your `settings.json` ? 

```
Explorer › File Nesting: Patterns
Controls nesting of files in the explorer. [Explorer › File Nesting: Enabled](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) must be set for this to take effect. Each Item represents a parent pattern and may contain a single * character that matches any string. Each Value represents a comma separated list of the child patterns that should be shown nested under a given parent. Child patterns may contain several special tokens:

${capture}: Matches the resolved value of the * from the parent pattern
${basename}: Matches the parent file's basename, the file in file.ts
${extname}: Matches the parent file's extension, the ts in file.ts
${dirname}: Matches the parent file's directory name, the src in src/file.ts
*: Matches any string, may only be used once per child pattern
```

**Comment by bogdanmarinescu** [comment]
Sorry, now I understand your question.
You have to write:
```
"explorer.fileNesting.patterns": {
        "Cargo.toml": ""
    },
```
in order to disable it.

**Pull request merged**
