### PR TITLE
feat: make trait assoc items become inactive due to cfg 

### LINKED ISSUE #12394: Associated methods removed by conditional compilation are not dimmed
**rust-analyzer version**: 7e95c14ea 2022-05-17 stable

**rustc version**: 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: Windows 10 x64, VSCode 1.67.2

Screenshot:

dimmed

### PR DESCRIPTION
**Pull request by DesmondWillowbrook**
fixes #12394

### CODE REVIEW

**Comment by DesmondWillowbrook** [comment]
Narrowed down the logic for ignoring the assoc items to https://github.com/rust-lang/rust-analyzer/blob/1883d1f14146959cfa9cdf1ed43e5d1ad013e07e/crates/hir-def/src/data.rs#L475-L484

**Comment by DesmondWillowbrook** [comment]
Searching for `is_cfg_enabled` is the way to go for finding places where things are filtered without emitting a diagnostic.

**Comment by DesmondWillowbrook** [comment]
@flodiebold 
For the plumbing you mentioned, most sub-items are filtered in `hir-def/src/adt`, while inactive diagnostics are emitted in `hir-def/src/nameres/collector` (for inactive module items). Additionally, the diagnostics structs are only available to modules in the `nameres` module. I saw #8973 which moved diagnostics to its current position.

Should I try to thread a diagnostics vec for all the functions that filter cfg'd fields? Is there a particular reason why fields are filtered at the AST stage, instead of the HIR stage like module items?

**Review by DesmondWillowbrook — COMMENTED** [review]
[Discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/fix.20trait.20assoc.20item.20not.20becoming.20inactive.20due.20to.20cfg)

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by lnicola** [comment]
image

**Pull request merged**
