### PR TITLE
fix: Remove a redundant `<never-to-any>` from adjustment hints for let-else

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Before:

After:

I'm not sure why an adjustment is there at all, given that `else` block in `let-else` must always evaluate to `!`, but we can suppress it I guess...

Continuation of #13749

### CODE REVIEW

**Comment by Veykril** [comment]
We seem to emit a never to never coercion there

**Comment by Veykril** [comment]
So ye this is most likely a never to never coercion as can be seen here
image

Now, the question is whether this coercion makes sense? (Though I assume rust also does it, in which case we should keep it)
The proper fix I think would be to probably reveal the types in the adjustment HIR api (I was lazy and figured I wouldn't need them for now which is why they are currently missing from the HIR api) and then check if this is a never to never coercion.

**Comment by WaffleLapkin** [comment]
Having types in the tooltips can be interesting too 👀

**Comment by Veykril** [comment]
Certainly, fwiw adding types to the API is only a matter of transforming the `hir_ty::Ty` into a `hir::Type` and exposing them iwth the adjustment kinds.

**Pull request closed without merging**
