### PR TITLE
fix: ProjectWorkspace::DetachedFiles does not contain toolchain and target_layout

### PR DESCRIPTION
**Pull request by oooutlk**
Avoid using these fields in `load_cargo::load_crate_graph()`.

### CODE REVIEW

**Comment by oooutlk** [comment]
I noticed that using these two fields are not mistakes but an incomplete effort to add them for DetachedFiles. Unfortunately I failed in compiling these code while my project is depending on 0.0.202, that’s why I thought it was a bug. Isn’t it? However I’ll close this pr.

**Comment by lnicola** [comment]
Note that auto-publishing is currently broken, probably because of some breaking change in a dependency of `cargo-workspaces`: https://github.com/rust-lang/rust-analyzer/actions/runs/8044749724/job/21968837388.

CC @pksunkara

**Comment by pksunkara** [comment]
Looks like gix-actor 0.30.1 patch release is broken. @byron Are you willing to yank it and/or release a fix?

**Comment by Byron** [comment]
The version of `gix-actor` you are referring to [is already yanked](https://crates.io/crates/gix-actor/0.30.1). It can't be fixed differently, unfortunately.

**Comment by lnicola** [comment]
Thanks, publishing succeeded in https://github.com/rust-lang/rust-analyzer/actions/runs/8044749724/job/22001956273.

**Pull request closed without merging**
