### PR TITLE
feat: Implicit format args support

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/11260
Fixes https://github.com/rust-lang/rust-analyzer/issues/11296

image
Too lazy to make a gif of this right now (would probably be good to show renaming)

### CODE REVIEW

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust-analyzer/assets/308347/20bcb7f6-cfa2-4550-a2ba-a524ab52cba3

**Comment by nyurik** [comment]
so now we can re-enable clippy lint for this? :)  Assuming it will only work by default in the "all params can be included" context.  If its a mixed case, that would stay as pedantic.

**Comment by Veykril** [comment]
Yes you should be able to re-enable it now.

**Pull request merged**
