### PR TITLE
Fix missing fields check on destructuring assignment

### LINKED ISSUE #12838: Error reported when using a destructuring assignment with ignored field
```rust
            struct Demo {
                a: i32,
                c: i32,
            }

            let demo = Demo { a: 6, c: 6 };

            let mut a = 2;

            Demo { a , .. } = demo;
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=06a9b2123942df3e008b9edd5e3ca885

this compiles fine, but rust analyzer thinks the `c` field isn't ignored

Screen Shot 2022-07-20 at 7 46 04 PM

rust 1.62.1
rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17)

### PR DESCRIPTION
**Pull request by lowr**
Fixes #12838 

When checking if the record literal in question is an assignee expression or not, the new fn `is_assignee_record_literal` iterates over its ancestors until it is sure. This isn't super efficient, as we don't cache anything and does the iteration for every record literal during missing fields check. Alternatively, we may want to have a field like `assignee` on `hir_def::Expr::{RecordLit, Array, Tuple, Call}` to tell if it's an assignee expression, which would be O(1) when checking later but have some memory overhead for the field.

### CODE REVIEW

**Review by Veykril — COMMENTED** [review]
Instead of querying the source after lowring for whether this is in assignee position I'd instead add that information to the hir `Expr::RecordLit` variant. That should be less messy than having to resort to the source map. Just adding a bool to `ExprCollector` tracking whether its lowering in an assignee position right now or not seems sufficient.

**Comment by lowr** [comment]
Agreed, I'll rewrite the patch. Can I also add "that information" to other applicable variants, namely `ArrayExpr`, `TupleExpr`, and `CallExpr`? Though not immediately used, they'd be handy in situations like this.

**Comment by Veykril** [comment]
Ye that should be fine

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Pull request merged**
