### PR TITLE
Don't compute layout if `TargetDataLayout` is not available

### PR DESCRIPTION
**Pull request by HKalbasi**

### CODE REVIEW

**Comment by AThilenius** [comment]
I'll give it a go. These the correct instructions for installing an extension from a git branch? https://stackoverflow.com/questions/50714638/install-extension-from-a-specific-repo-branch-on-github

**Comment by lnicola** [comment]
https://rust-analyzer.github.io/manual.html#building-from-source

**Comment by gaoqiangz** [comment]
I didn't see the error anymore :-)

**Pull request merged**
