### PR TITLE
minor: Remove unneeded conversions

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Noticed thanks to hover when browsing in the repo.

### CODE REVIEW

**Comment by Veykril** [comment]
Surprised clippy doesn't catch that

**Comment by ChayimFriedman2** [comment]
In general it cannot, passing the reflexive `from` is sometimes sensible (I think?) Maybe it can detect with `Option::map()` though.

**Comment by Veykril** [comment]
It does usually catch no-op from/into calls )from what I remember), though I suppose it might not when its used as a function pointer.

**Comment by ChayimFriedman2** [comment]
It does when they are called directly, it can't generally when they are passed as higher-order functions.

**Pull request merged**
