### PR TITLE
Remove crate graph deduplication logic

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/17748

### CODE REVIEW

**Comment by davidbarsky** [comment]
Not opposed to the removal, but what's the thinking, if you don't mind my asking?

**Comment by Veykril** [comment]
Cargo runs proc macros in the workspace directory, not the crate manifest
dir, which we need to replicate and as such all crates are unique wrt to
their workspace. Cargo also will expose this in an env var in the future
(if it doesn't already on stable)

**Comment by max-sixty** [comment]
Thanks @Veykril !

**Pull request merged**
