### PR TITLE
Rename generator to coroutine

### PR DESCRIPTION
**Pull request by mohe2015**
Follow the rename in nightly (see https://blog.rust-lang.org/inside-rust/2023/10/23/coroutines.html)

This makes it much easier to test code with the nightly compiler.

### CODE REVIEW

**Comment by Veykril** [comment]
The chalk changes should be published now I think, so you can adapt that

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by lnicola** [comment]
changelog internal (first contribution) rename `generator` to `coroutine`

**Pull request merged**
