### PR TITLE
internal: Rename crates after removing libs from workspace

### PR DESCRIPTION
**Pull request by davidlattimore**

### CODE REVIEW

**Comment by davidlattimore** [comment]
Issue #15038

**Comment by davidlattimore** [comment]
Currently autopublish fails with:
```
error: failed to select a version for the requirement `ra_ap_la-arena = "^0.3.1"`
```

This is because the libs were still present in the workspace when we did the rename, so things that depend on libs crates like la-arena were changed to depend on ra_ap_la-arena.

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
@davidlattimore do you want to trigger an out-of-band auto-publish to see what happens now?

**Comment by davidlattimore** [comment]
> @davidlattimore do you want to trigger an out-of-band auto-publish to see what happens now?

Thanks @lnicola. If it's easy to do, sure. I guess I could also change the workflow so that it's automatically triggered whenever changes to `autopublish.yaml` are pushed to `master`.

**Comment by lnicola** [comment]
Failed with an ownership error in https://github.com/rust-lang/rust-analyzer/actions/runs/5389402967/jobs/9783310640.

**Comment by lnicola** [comment]
> If it's easy to do, sure.

Yeah, it's super easy, but I didn't know if you wanted the auto-published versions to match yesterday's release exactly.

> Failed with an ownership error

@matklad can you do some crates.io magic (see https://crates.io/crates/ra_ap_intern vs. https://crates.io/crates/ra_ap_flycheck)?

**Comment by matklad** [comment]
invite for [rust-lang-owner](https://crates.io/users/rust-lang-owner) sent

**Comment by lnicola** [comment]
Pinging @pietroalbini just in case :-).

**Pull request merged**
