### PR TITLE
fix: nested doc comment code blocks don't render in hover preview

### LINKED ISSUE #14383: Nested markdown fenced code blocks in doc comments aren't renedered properly
I have the following code:

```rust
enum BlockElement {
  // ...

  /// Fenced code block.
  ///
  /// # Examples
  ///
  /// `````markdown
  /// ```
  /// code block
  /// ```
  ///
  /// ```rust
  /// code block
  /// ```
  /// `````
  FencedCodeBlock {/* ... */},

  // ...
}
```

I expect the doc comment to be rendered as (screenshot from rustdoc output):

image

But instead when I hover over `FencedCodeBlock` in VS Code I get this:

image

Or when triggering auto-completion in Helix:

image

**rust-analyzer version**: 0.3.1435-standalone (f1e51afa4 2023-03-12)

**rustc version**: 1.70.0-nightly (7b4f48927 2023-03-12)

**relevant settings**: I don't think there are any

### PR DESCRIPTION
**Pull request by DesmondWillowbrook**
fixes #14383

### CODE REVIEW

**Comment by DesmondWillowbrook** [comment]
Right now, I'm coming across test failures like this:
```
  left: `"\n```rust\nfn some_rust() {}\n```"`,
 right: `"```rust\nfn some_rust() {}\n```"`', crates/rust-analyzer/src/markdown.rs:108:9
```
It seems that the `pulldown_cmark` is not emitting an event for the `\n` before the code block.

**Comment by DesmondWillowbrook** [comment]
Is this behavior unwanted? I think not, but I'm not sure.

@rustbot r?

**Comment by Veykril** [comment]
Ah sorry, I missed this PR. Not sure about the `pulldown_cmark` thing, I would expect it to work properly there, its what rustdoc should be using as well). Maybe looking at `crates\ide\src\doc_links.rs` will help you, we are doing a markdown transformation there with the crate as well.

**Comment by DesmondWillowbrook** [comment]
This behavior also occurs in the `doc_links` functions. Since that functionality is already used to process markdown text, then this behavior is apparently already present in RA right now.

**Comment by Veykril** [comment]
Sorry this kind of fell of my radar, though I think we bumped pulldown-cmark's version now so it might be fixed?

**Pull request closed without merging**
