### PR TITLE
Support `Pointee` trait

### LINKED ISSUE #13992: Pointer metadata (RFC 2580) is not supported
```Rust
#![feature(ptr_metadata)]

use core::ptr::Pointee;

fn main() {
    let x: <[&str] as Pointee>::Metadata = todo!();
    let mut y = x;
    y = 2;
}
```

Rustc accepts the above code but r-a reports a type mismatch between `<[&str] as Pointee>::Metadata` and `i32`. It is probably due magic implementation of `Pointee` trait for types.

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #13992

### CODE REVIEW

**Comment by HKalbasi** [comment]
This PR upgrades chalk which uses syn2. Is it a problem?

**Comment by Veykril** [comment]
I'd like to wait until we can move all our dependencies over to versions using syn 2 so we don't build syn 1 and syn 2

**Comment by lnicola** [comment]
That mean we won't be able to get any juicy `chalk` fixes until we switch, not that it's really active these days.

I have a draft PR for `salsa` at https://github.com/salsa-rs/salsa/pull/442, but it still needs some work.

**Comment by Veykril** [comment]
fwiw, we can't really use upstream salsa as is. There are some commits on master that the latest release doesn't have. And those commits cause a considerable slow down in rust-analyzer.

**Comment by HKalbasi** [comment]
Now that we don't publish crates, isn't possible to use git dependency to our forks? Either for salsa to upgrade syn, or for chalk to downgrade syn.

**Comment by Veykril** [comment]
Huh, it was slower by *a lot* when I tested this back then

**Comment by lnicola** [comment]
Yeah, but then Nikos made some changes and brought it within 10% of the original.

**Comment by HKalbasi** [comment]
I tried to see the compile time effect of this branch using `cargo build --timings` and it seems the `syn2` is not on the critical path. The current critical path is `quote > syn1 > salsa-macros > salsa > base-db > hir-expand > hir-def > hir-ty` and the maximum path including `syn2` is `quote > syn2 > chalk-derive > chalk-ir > chalk-solve > chalk-recursive > hir-ty` which has ~4 seconds slack time. And the reported time by cargo on my machine is `1m 15s` this branch vs `1m 13s` on master.  The situation is probably worse in CI which has less cores than my machine, but it shouldn't be *that bad* as the syn takes 12s to compile so I guess a ~6 delay? Let's see.

Is there any other problem in mixing `syn`s other than compile time?

**Comment by lnicola** [comment]
I hope we could eat the `syn 2` slowdown for now, because there's some great goodies coming up in `chalk`.

**Pull request merged**
