### PR TITLE
internal: skip associated items and call `generic_implements_goal` earlier in method resolution

### PR DESCRIPTION
**Pull request by davidbarsky**
This is a small change whose correctness I'm not entirely convinced of, but based on the discussion in https://github.com/rust-lang/rust-analyzer/issues/6432 and my testing in https://github.com/oxidecomputer/omicron, this _seems_ to provide faster completions, especially when it comes to flyimport-based ones.

_Without_ these changes, I'm seeing completions take roughly 808ms cold and 570ms warm. _With_ these changes, I'm seeing completions take 473ms cold and 55-90ms warm.

### CODE REVIEW

**Comment by davidbarsky** [comment]
(Note that these numbers are coming from my M1 Pro-based MacBook Pro. Your experience may vary.)

**Comment by Veykril** [comment]
That slow down does not surprise me, trait solving is expensive, and now you are solving before checking the validity of a candidate.

**Comment by Veykril** [comment]
From a quick look we can (very very slightly only) optimize `is_valid_candidate` for this call path though. We know that our assoc items here come from a trait, meaning this branch here cannot be hit ever https://github.com/rust-lang/rust-analyzer/blob/e2cfed178976437015b6a50176c9280dbc445e3f/crates/hir-ty/src/method_resolution.rs#L1403-L1414 as well as https://github.com/rust-lang/rust-analyzer/blob/e2cfed178976437015b6a50176c9280dbc445e3f/crates/hir-ty/src/method_resolution.rs#L1480-L1529

additionally the visibility check here https://github.com/rust-lang/rust-analyzer/blob/e2cfed178976437015b6a50176c9280dbc445e3f/crates/hir-ty/src/method_resolution.rs#L1397-L1402 and here https://github.com/rust-lang/rust-analyzer/blob/e2cfed178976437015b6a50176c9280dbc445e3f/crates/hir-ty/src/method_resolution.rs#L1440-L1445
should be unnecessary. The visibility of trait assoc items is the visibility of the trait which we can either check once prior to looping, or ignore if the check is implicitly done somewhere already (not 100% about that). This gets rid of a few database accesses as well as inserting extra query dependencies.

(Note these are only irrelevant for this one call path here, not in general for the other callers of the `is_valid_` functions)

**Comment by davidbarsky** [comment]
> That slow down does not surprise me, trait solving is expensive, and now you are solving before checking the validity of a candidate. I'm more surprised that the change actually helps with completion speed here in your scenario.

Going off a previous profile[^1] I ran, rust-analyzer is doing a _lot_ of `is_valid_candidate` checks—for 300 traits, rust-analyzer did 13856 `is_valid_candidate` calls. The approach in this PR reduced the number of `is_valid_candidate` calls to 372.

> (Note these are only irrelevant for this one call path here, not in general for the other callers of the `is_valid_` functions)

I'll try out your suggested changes! If it works out well, I'll inline the reduced `is_valid_` functions into a single function and document that function should only be called from `iterate_trait_method_candidates`.

---

[^1]:
<details>
    <summary>The aforementioned previous profile</summary>

```
    783ms handle_completion
        30ms CompletionContext::new
          13ms CompletionContext::analyze
            13ms Semantics::analyze_impl (2 calls)
            13ms infer:wait @ detail = "new"  (2 calls)
              13ms infer_query
                 7ms iterate_method_candidates_dyn @ mode = Path name = Some(Name(Text("read"))) traits_in_scope_len = 32  (4 calls)
                   4ms iterate_method_candidates_for_self_ty @ name = Some(Name(Text("read")))  (2 calls)
                     4ms iterate_inherent_methods @ name = Some(Name(Text("read")))  (2 calls)
                       2ms impls_for_self_ty @ name = Some(Name(Text("read")))
                         2ms is_valid_candidate (3 calls)
                           2ms is_valid_fn_candidate (3 calls)
                             2ms run_in_snapshot
                               2ms trait_solve::wait (4 calls)
                   2ms iterate_method_candidates_with_autoref @ name = Some(Name(Text("Some")))  (3 calls)
                     2ms iterate_method_candidates_by_receiver @ name = Some(Name(Text("Some")))  (7 calls)
                       2ms iterate_trait_method_candidates @ name = Some(Name(Text("Some")))  (15 calls)
                         2ms is_valid_candidate (1947 calls)
                           1ms is_valid_fn_candidate (1847 calls)
          16ms CompletionContext::expand
            16ms SourceBinder::to_module_def (4 calls)
            16ms crate_def_map:wait (9 calls)
       719ms import_on_the_fly_method @ potential_import_name = ""
         714ms import_assets::search_for_imports
           714ms import_assets::search_for
             714ms import_assets::trait_applicable_items
                12ms items_with_name @ name = "" assoc_item_search = AssocItemsOnly crate = Some("omicron_common")
                  12ms find_items
                     5ms crate_symbols
                       1ms module_symbols (2 calls)
                     6ms query_external_importables
                     6ms search_dependencies @ query = Query { query: "", lowercased: "", search_mode: Fuzzy, assoc_mode: AssocItemsOnly, case_sensitive: false }
               702ms iterate_method_candidates
               702ms iterate_method_candidates_dyn @ with_local_impls = 300 traits_in_scope = 300 name = None
                 702ms iterate_method_candidates_dyn @ mode = MethodCall name = None traits_in_scope_len = 300
                   702ms iterate_method_candidates_with_autoref @ name = None  (2 calls)
                     702ms iterate_method_candidates_by_receiver @ name = None  (6 calls)
                         4ms iterate_inherent_methods @ name = None  (13 calls)
                           4ms impls_for_self_ty @ name = None  (6 calls)
                             4ms is_valid_candidate (42 calls)
                               4ms is_valid_fn_candidate (42 calls)
                                 4ms run_in_snapshot (42 calls)
                                   2ms trait_solve::wait (72 calls)
                                     2ms trait_solve_query @ detail = "SendSyncUnwindSafeDrain"  (4 calls)
                       697ms iterate_trait_method_candidates @ name = None  (13 calls)
                           2ms find_path_prefixed (9 calls)
                         495ms is_valid_candidate (13856 calls)
                           489ms is_valid_fn_candidate (11784 calls)
                             472ms run_in_snapshot (11784 calls)
                                 2ms crate_def_map:wait (4115 calls)
                                10ms fill_with_inference_vars (23568 calls)
                                 2ms generic_params_query (1332 calls)
                                11ms rollback_to (11784 calls)
                         189ms trait_solve::wait (1093 calls)
                           187ms trait_solve_query @ detail = "TryStreamExt"  (771 calls)
                              17ms impl_datum (164 calls)
                                 9ms parse_macro_expansion (270 calls)
                                   7ms macro_expand (270 calls)
                                     1ms parse_query @ file_id = FileId(12423)
                               2ms lang_item_query (2 calls)
                                 2ms crate_lang_items_query (2 calls)
                                   2ms collect_lang_item (480 calls)
           3ms render_method (21 calls)
             3ms body_with_source_map_query (8 calls)
               2ms parse_query @ file_id = FileId(12438)
        31ms iterate_method_candidates
        31ms iterate_method_candidates_dyn @ with_local_impls = 31 traits_in_scope = 31 name = None
          31ms iterate_method_candidates_dyn @ mode = MethodCall name = None traits_in_scope_len = 31
            31ms iterate_method_candidates_with_autoref @ name = None  (2 calls)
              31ms iterate_method_candidates_by_receiver @ name = None  (6 calls)
                 2ms iterate_inherent_methods @ name = None  (13 calls)
                   2ms impls_for_self_ty @ name = None  (6 calls)
                     1ms is_valid_candidate (42 calls)
                       1ms is_valid_fn_candidate (42 calls)
                         1ms run_in_snapshot (42 calls)
                29ms iterate_trait_method_candidates @ name = None  (13 calls)
                  26ms is_valid_candidate (801 calls)
                    26ms is_valid_fn_candidate (710 calls)
                      25ms run_in_snapshot (710 calls)
                   1ms render_method (6 calls)
                     1ms body_with_source_map_query (2 calls)
                       1ms parse_query @ file_id = FileId(12156)  (2 calls)
```
<details>

**Comment by davidbarsky** [comment]
> I'll try out your suggested changes! If it works out well, I'll inline the reduced `is_valid_` functions into a single function and document that function should only be called from `iterate_trait_method_candidates`.

You are correct that the optimizations are slight, but they are noticeable! Thanks for the tip.

**Comment by Veykril** [comment]
I'm not happy merging the first change of this fwiw. The slow down is just too big for this to be considered.

**Comment by davidbarsky** [comment]
Closing this PR in favor of opening a new one in order to make the conversation history more legible.

**Pull request closed without merging**
