### PR TITLE
Document nvim 0.10 `inlay_hint`

### PR DESCRIPTION
**Pull request by rikhuijzer**
It took me a few hours to figure out how to enable inlay type hints on Nvim 0.10 with `lspconfig`. `rustaceanvim` has already dropped support for them (https://github.com/mrcjkb/rustaceanvim/discussions/46#discussioncomment-7518669) and most other plugins, like `rust-tools`, are depreciated in favor of `rustaceanvim`.

This PR documents how to enable the inlay hints on Neovim 0.10 and later. I've tested this and changing the `on_attach` function is the only step that is required.

### CODE REVIEW

**Comment by Veykril** [comment]
Shouldn't such documentation belong to the rustaceanvim docs?

**Comment by rikhuijzer** [comment]
> Shouldn't such documentation belong to the rustaceanvim docs?

Good question. I don't think so. I myself run without any `rust-tools` or `rustaceanvim` and when I compare the GitHub stars of `rustaceanvim` and `lspconfig`, it looks like many people do so too.

This documentation change is in the `lspconfig` section of the docs. Inlay hints require only Neovim, `coc-rust-analyzer`, and `lspconfig`.

**Comment by rikhuijzer** [comment]
Thanks, @Veykril

**Pull request merged**
