### PR TITLE
feat: Diagnose unresolved field, method call and call expression

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by lenstr** [comment]
Hi! Just updated to the latest version of rust-analyzer and now all my diesel models are red

image

**Comment by Veykril** [comment]
You can put `unresolved-method` in the `rust-analyzer.diagnostics.disabled` setting to silence the warning, diesel is known to cause problems for us so this is not too surprising I guess... (Let me make that an issue though)

**Comment by martijnarts** [comment]
Hey all, I don't know if this helps but I'm seeing an unresolved-field error on a field that definitely exists and compiles just fine. I think the problem is actually the weird dependencies I've introduced into my workspace modules though. I've reproduced it here: https://github.com/martijnarts/ra-unresolved-field-repro

Here's what it looks like when breaking:

how-it-breaks

**Comment by Veykril** [comment]
That looks like an interesting issue (with a nice preproduction). Could you open that as a new issue?

**Comment by martijnarts** [comment]
Created here: https://github.com/rust-lang/rust-analyzer/issues/14296

**Pull request merged**
