### PR TITLE
Cancelable Initialization

### PR DESCRIPTION
**Pull request by schrieveslaach**
This commit provides additional initialization methods to Connection in order to support CTRL + C sigterm handling.

In the process of adding LSP to Nushell (see https://github.com/nushell/nushell/pull/10941) this gap has been identified.

### CODE REVIEW

**Comment by Veykril** [comment]
Seems fine to add for now, though long term we should consider what matklad wrote here https://github.com/rust-lang/rust-analyzer/pull/14582#discussion_r1186510128
@bors r+

**Comment by Veykril** [comment]
Looks like this needs a rebase + Cargo.lock update

**Comment by schrieveslaach** [comment]
@Veykril, I rebased this branch. Please, check it out again.

**Comment by schrieveslaach** [comment]
@Veykril, are you planning a release of this crate in the near future? @fdncred would love to get rid of a branch dependency in Nushell (which I can understand).

**Comment by schrieveslaach** [comment]
And thank you very much for accepting this PR.

**Comment by Veykril** [comment]
Ye, we can cut a release for this. Given the changes a patch release should be fine (since we are below 1.0 with the lib still). Though I'm a bit busy right now

**Comment by Veykril** [comment]
Oh sorry, I completely forgot to push the release for this, `0.7.5` should be out now

**Pull request merged**
