### PR TITLE
internal: Report type metrics for patterns

### PR DESCRIPTION
**Pull request by Veykril**
```
❯ cargo run --release -p rust-analyzer -q analysis-stats --memory-usage .
Database loaded:     2.09s, 218mb (metadata 275.07ms, 21mb; build 1.29s, 504kb)
  crates: 44, mods: 916, decls: 19582, fns: 14631
Item Collection:     14.33s, 472mb
  exprs: 420422, ??ty: 68 (0%), ?ty: 141 (0%), !ty: 1
  pats: 82968, ??ty: 11 (0%), ?ty: 10 (0%), !ty: 178
Inference:           47.84s, 745mb
Total:               62.16s, 1217mb
```
We currently have 178 mismatches on r-a itself

### CODE REVIEW

**Comment by Veykril** [comment]
This also adds them to the type related metrics, not sure if we want to group them together, maybe having them be split into pats and exprs would be nicer for the metrics webpage?
r? @lnicola

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
We might want to split them to make it easier to figure out what changed when they increase, but no strong opinion either way.

**Comment by Veykril** [comment]
Sounds reasonable
@bors r=lnicola

**Comment by Veykril** [comment]
Unsure how the metrics website works but will this need changes for the new category to be acknowledged? And I assume we shouldn't change the old key for expressions (it has no expression prefix right now, left it as is to not break things).

**Comment by lnicola** [comment]
We'll find out soon enough. I remember that code want much fun to work on.

**Comment by Veykril** [comment]
It seems to just work 🎉 
image

**Pull request merged**
