### PR TITLE
Add support for impl traits in type aliases

### PR DESCRIPTION
**Pull request by unexge**
Fore more detail about impl traits in type aliases you can see the [RFC](https://rust-lang.github.io/rfcs/2515-type_alias_impl_trait.html).

I've mostly copied related functions for return type impl traits for type alias impl traits and modified accordingly.

Fixes https://github.com/rust-lang/rust-analyzer/issues/13824

### CODE REVIEW

**Comment by lowr** [comment]
Super excited to see TAIT coming to r-a! I was looking at the [stabilization report][report] and its accompanying [hackmd] the other day and I think we need to consider a few additional things.

- Type mismatches between opaque types and non-opaque types shouldn't be reported when in their defining scope, because they actually aren't type mismatches but defining uses. For example:

    ```rust
    mod inner {
        pub type Opaque = impl Clone;
        fn defining_scope() {
            let a: Opaque = 0i32; // defining use, shouldn't be reported as type mismatch
            let a: i32 = a;       // same as above
        }
    }
    
    fn non_defining_scope() {
        let a: inner::Opaque = 0i32; // now this *is* a type mismatch that should be reported
    }
    ```
    
    (Ideally, it'd be nice to report type mismatches when defining uses impose different types for the hidden type of a TAIT (e.g. `let a: Opaque = 0; let b: Opaque = "asdf";`), but that would require tracking the hidden type of each TAIT so maybe not for this initial implementation)

- How do we want to display TAITs? Personally speaking, showing the alias name is more favorable than `impl Trait` as there would be clear distinction between opaque types (we can get the name of the alias from `ImplTraitId` right?).

The latter point is rather bikeshedding and it's fairly easy to change so it doesn't block for this PR to land I guess, but I think we want to at least address the former point.

[report]: https://github.com/rust-lang/rust/issues/63063#issuecomment-1354392317
[hackmd]: https://hackmd.io/tB3V8MP5S66zHIWTUdRvQw

**Comment by unexge** [comment]
I'm trying to learn Chalk 😄 Couldn't figure out what is best `TyKind` to lower TAITs. This PR currently lowers them to `TyKind::OpaqueType`, but it's a placeholder type and it only equals to [itself](https://rust-lang.github.io/chalk/book/types/rust_types/alias.html#alias-placeholders) and because of that, in, `let a: Opaque = 0i32; let a: i32 = a;` the second assignment fails. I've also checked what we are [doing for RPITs](https://github.com/rust-lang/rust-analyzer/blob/7449f9fa1018b4f3682eb176b65ad5fcd8d56d56/crates/hir-ty/src/infer.rs#L592-L622), seems like we are converting them to `TyKind::InferenceVar`s with correct bounds and then Chalk resolves (or substitutes, not sure what is the correct term 😄) them to concrete types, and thanks to that it correctly fails in:
```rust
fn foo() -> impl Clone {
    if true {
        return 0i32;
    }
    false 
 // ^^^^^ expected i32, found bool
}
```
But I think we need a mix of them, it should be `TyKind::InferenceVar` + concrete type in defining scope but it should be `TyKind::OpaqueType` in the non-defining scope.

**Comment by Veykril** [comment]
Note, the current design requires looking into all bodies for defining uses of TAITs which is obviously a problem for IDEs, so that might be adjusted https://rust-lang.zulipchat.com/#narrow/stream/315482-t-compiler.2Fetc.2Fopaque-types/topic/TAITs.20and.20lazy.20parsing

**Comment by Veykril** [comment]
I'll close this due to inactivity, feel free to come back to this (either by re-opening or opening a new PR)

**Pull request closed without merging**
