### PR TITLE
Don't retry requests that have already been cancelled

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by Veykril** [comment]
Do we auto-publish libraries(`lib` crates that is) on this repo? I don't remember

**Comment by lnicola** [comment]
We don't.

**Comment by Veykril** [comment]
Just realized @matklad is the sole owner of lsp-server on crates.io, given we vendored this we should probably add the rust-lang r-a team and the rust-lang-owner as owners for the crate like was done for the autopublished packages

**Pull request merged**
