### PR TITLE
Move salsa fork in-tree

### PR DESCRIPTION
**Pull request by Veykril**
No one else is supposed to rely on it anyways, this makes it easier to edit.

### CODE REVIEW

**Comment by Veykril** [comment]
TODO: Replace insta with expect-test to cut down on dev-deps

**Comment by davidbarsky** [comment]
oh, thanks for doing this, i was going to send a PR with this, but i'm glad you got there first!

**Comment by lnicola** [comment]
I was worried this would slow down the builds, but it doesn't seem noticeable.

**Comment by lnicola** [comment]
@dbarsky does `tracing` have something like https://docs.rs/test-log/?

image

**Comment by davidbarsky** [comment]
> @dbarsky does `tracing` have something like https://docs.rs/test-log/?
> 
> 
> 
> image
> 
> 
> 
> EDIT: nvm, that's literally `test-log` :grinning:.

slightly incorrect name, but yes, test-log does this.

**Comment by Veykril** [comment]
> I was worried this would slow down the builds, but it doesn't seem noticeable.

Why should it?

**Comment by lnicola** [comment]
We exclude the workspace crates from the GitHub cache.

**Pull request merged**
