### PR TITLE
Fix add reference action on macros.

### LINKED ISSUE #13219: Add string reference code action wrong positon, when string generated by `format!()`
**rust-analyzer version**:
rust-analyzer 0.3.1194-standalone (67920f797 2022-09-04)
**rustc version**: (eg. output of `rustc -V`)
rustc 1.65.0-nightly (2befdefdd 2022-08-06)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

### PR DESCRIPTION
**Pull request by mdx97**
Before we were using the range of the corresponding expression node in the macro expanded file, which is obviously incorrect as we are setting the text in the original source.

For some reason, the test I added is failing and I haven't found a way to fix it. Does anyone know why `check_fix` wouldn't work with macros? Getting this error:

```text
thread 'handlers::type_mismatch::tests::test_add_reference_to_macro_call' panicked at 'no diagnostics', crates/ide-diagnostics/src/handlers/type_mismatch.rs:317:9
```

closes #13219

### CODE REVIEW

**Comment by Veykril** [comment]
The test is failing because `String` is no defined (tests don't know about std). so just add a `struct String;` to your fixture and it should work

**Comment by mdx97** [comment]
@Veykril thanks Lukas. I will fix that up after work today.

**Comment by mdx97** [comment]
I just went ahead and used a `u64` instead.

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Pull request merged**
