### PR TITLE
Return bool instead of Result<(),()> for limit::check

### PR DESCRIPTION
**Pull request by nyurik**
The `Result<(),()>` is a very strange construct,
and even Clippy is unhappy about it :)

This PR only changes that API to return a bool.

I did a cursory check in intellij rust plugin,
and didn't find any reference to this func,
so I suspect it is mostly used internally.

### CODE REVIEW

**Comment by lnicola** [comment]
I suspect using `Result` here was [intentional](https://github.com/rust-lang/rust-analyzer/pull/9453#issuecomment-872598838). It seems a nice change with the `#[must_use]` you've added, but the others might not agree.

**Comment by nyurik** [comment]
> > I did a cursory check in intellij rust plugin, and didn't find any reference to this func,
> 
> Um, what? sweat_smile

Well, i figured that this might be a public api of sorts, so tried to do some digging to see if it was used anywhere outside of the rust analyzer ... somewhere somehow i heard it was being used by intellij, so went digging... not very successfully :D

**Comment by lnicola** [comment]
No, only a small part of RA (the proc macro server) was used by IntelliJ, and it's been upstreamed to rustc, so it's not available to everyone. The two plugins are completely independent otherwise.

As for this specific case, it's maybe less idiomatic, but such are the project style conventions. The Result makes it clear when you should stop (you got an Err), unlike a bool which can be ambiguous (what does true mean? are we fine to go on or did we reach the limit?). Ideally, it would probably be an enum instead, but nobody bothered to change it.

**Comment by nyurik** [comment]
thx for the explanation.  I just felt a bit weird about the strangest contraption I have seen yet - the `Result<(),()>` -- looks like a weird smiley of sorts :)  But feel free to close without merging, not a biggie

**Comment by nyurik** [comment]
P.S. Note that there are a number of other `check` functions that look somewhat similar - but they do return a bool i think

**Comment by lnicola** [comment]
Yeah, so I don't think it's worth the churn right now, especially since we're against running `clippy` with the default set of lints. We might switch to an enum in the future, but `bool` seems strictly worse.

**Pull request closed without merging**
