### PR TITLE
Fix highlighting of byte escape sequences

### PR DESCRIPTION
**Pull request by oxalica**
Currently non-UTF8 escape sequences in byte strings and any escape sequences in byte literals are ignored.

### CODE REVIEW

**Comment by oxalica** [comment]
I'm also thinking about highlighting erroneous escape sequences as a special color, instead of leaving them the same as literals. But there is only a similar `UnresolvedReference` currently. Not sure if that's a good idea since they should already be marked by cargo-check as errors.

**Comment by oxalica** [comment]
>> I'm also thinking about highlighting erroneous escape sequences as a special color, instead of leaving them the same as literals. But there is only a similar `UnresolvedReference` currently. Not sure if that's a good idea since they should already be marked by cargo-check as errors.
>
> I think that's reasonable (I actually thought something like that would be cool while reviewing!). Do you want to implement it yourself, either in this PR or in a separate PR?

Implemented. I'm not sure how to provide a default color (like, red?) for different editors. I cannot find related color settings for `unresolvedReference` either.

**Comment by lowr** [comment]
Sorry for the delay. The implementation looks good! Do we also want to highlight invalid escape sequences in `highlight_escape_char()` and `highlight_escape_byte()`? Might be a little more complicated as it'd require implementing something similar to `IsString::escaped_char_ranges()` for `ast::Char` and `ast::Byte`.

As for the styling, it seems we have little control over it. [Looks like](fallback) we can define some fallback TextMate scopes, but seeing we don't provide it for `unresolvedReference`, it wouldn't block this PR to land I suppose.

[fallback]: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-textmate-scope-mappings

**Comment by oxalica** [comment]
> Do we also want to highlight invalid escape sequences in `highlight_escape_char()` and `highlight_escape_byte()`?

I don't think it will help much since `'` is not a reliable delimiter. If an invalid escape sequence occur after `'`, the lexer should very likely already blow up. We cannot determine the boundary of a char literal if something went wrong, considering `'lifetime` tokens.

> [Looks like](fallback) we can define some fallback TextMate scopes, but seeing we don't provide it for `unresolvedReference`, it wouldn't block this PR to land I suppose.

The link is broken. And I'm not familiar with TextMate thus prefer to skip it for now.

**Comment by lowr** [comment]
> I don't think it will help much since `'` is not a reliable delimiter. If an invalid escape sequence occur after `'`, the lexer should very likely already blow up. We cannot determine the boundary of a char literal if something went wrong, considering `'lifetime` tokens.

Makes sense. Could you add a comment explaining that rationale? r=me with it.

> The link is broken.

:man_facepalming: My bad, fixed.

@bors delegate+

**Pull request merged**
