### PR TITLE
minor: sync from downstream

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by lnicola** [comment]
Umm, these changes don't look right, where did they come from?

**Comment by lnicola** [comment]
I think I'm running into the same issue as in https://github.com/rust-lang/rust-analyzer/pull/13459, so I must be doing something really wrong :(.

**Comment by lnicola** [comment]
Okay, I _think_ it's fine now?

**Comment by lnicola** [comment]
r? @Veykril

Want to merge this so we unblock the other PRs?

**Comment by fasterthanlime** [comment]
> Okay, I _think_ it's fine now?

Seeing this just now, do you remember what you did that went wrong and what you did to make it right? I see a "merge master into sync-from-rust" between the two comments but not sure what the timeline is exactly.

**Comment by lnicola** [comment]
Not very well, but I think it was something really mundane like starting from a stale `master` branch.

**Pull request merged**
