### PR TITLE
fix: Some file watching related vfs fixes

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/15554, additionally it seems that client side file watching was broken on windows this entire time, this PR switches `DidChangeWatchedFilesRegistrationOptions` to use relative glob patterns which do work on windows in VSCode.

### CODE REVIEW

**Comment by lnicola** [comment]
Huh, it works for me :stuck_out_tongue:.

**Comment by Veykril** [comment]
Inbefore their file watcher works differently well between linux and windows

**Comment by Veykril** [comment]
Okay so VSCode just does not send a `workspace/didChangeWatchedFiles` notification when a file gets created even if it matches the glob pattern ... which I guess makes sense if you snapshot all existing files when we tell it what to watch? But at the same time, when will it ever send a created notification then ...?

**Comment by Veykril** [comment]
And no, this does not work for me whatsoever. Running `cargo add` yields no events from VSCode even 😕

**Comment by lnicola** [comment]
WDYM?

```
$ touch src/foo.rs # =>

[Trace - 9:57:23 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///Projects/hello/src/foo.rs",
            "type": 1
        },
        {
            "uri": "file:///Projects/hello/src/foo.rs",
            "type": 1
        }
    ]
}
```

**Comment by Veykril** [comment]
I don't get any such events from vscode :)

**Comment by lnicola** [comment]
Sounds like file watching is completely broken on Windows?

**Comment by Veykril** [comment]
Looks like it, tried it on my linux machine quickly and there touching does sent an event

**Comment by Veykril** [comment]
Huh, switching over to using relative patterns works! That's weird

**Pull request merged**
