### PR TITLE
fix: Don't show duplicated adjustment hints for blocks, ifs and matches

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Before:

After:

----

I want to improve adjustment hints, this is the first step :)

### CODE REVIEW

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by jonas-schievink** [comment]
Why are these coercions duplicated during type checking in the first place? To me that seems to be the better place to fix this.

**Comment by Veykril** [comment]
Thinking about this a bit, I don't think they are duplicating actually? The reborrows happen on every "pass" between blocks/expressions (which I believe matches rustc's behaviour, but would need to double check). Though the hints on the else block are obviously wrong, due to how we handle those block constructs.

**Comment by WaffleLapkin** [comment]
I don't think there is a meaningful difference between

1. `{ expr /* coercion */ } /* coercion */`
2. `{ expr /* coercion */ }`
3. `{ expr } /* coercion */`

They all result in the same "`<type of expr>` coerces to `<type of the whole expr>`" relationship, coercing the coercion does nothing I think.

**Comment by WaffleLapkin** [comment]
For example in case of reborrows specifically I'm pretty sure `&*&*a` and `&*a` are the same. Because `'a <= '0 <= '1` and `'a <= '1` are equivalent.

**Pull request merged**
