### PR TITLE
fix: Fix SyntaxContextID using incorrect self IDs

### PR DESCRIPTION
**Pull request by Veykril**
Follow up to https://github.com/rust-lang/rust-analyzer/issues/16200, there was another logical bug there.

### CODE REVIEW

**Comment by lnicola** [comment]
I've triggered a new nightly and will do today's release afterwards.

**Comment by Veykril** [comment]
Note this one wont cause panics, it might just cause macro $crate hygiene to resolve incorrectly.

**Comment by lnicola** [comment]
Aaand it's out. Happy New Year everyone!

**Pull request merged**
