### PR TITLE
Fix autoimport does nothing when importing trait that is `as _` imports

### PR DESCRIPTION
**Pull request by dfireBird**
This is not the final implementation only a draft I made to discuss upon and improve it as required.

Todo:
- [ ] Improve the implementation if required 
- [ ] Add tests

### CODE REVIEW

**Comment by Veykril** [comment]
Closing due to inactivity, feel free to re-open if you get back to it

**Comment by dfireBird** [comment]
Sorry @Veykril . I was actually waiting for someone to review the current code. It feels like a hack rather a solution. So I wanted a review before making the PR ready for merge.

**Comment by Veykril** [comment]
Ah apologies, I didn't realize you were waiting for feedback (to me it looked like a PR that was opened with the intention of follow up). I'm not quite sure what the question is but having a brief look at the diff I am a bit confused by what's done here. I would expect that the only thing to do here is drop the rename if it exists (as an underscore rename that is).

**Comment by dfireBird** [comment]
My bad I wasn't explicit enough that I need feedback. 

I too forgot what my implementation was doing and what my thought process was. I'll try to recollect and open a new PR with the steps described on why I did that.

**Pull request closed without merging**
