### PR TITLE
internal: Bump salsa

### PR DESCRIPTION
**Pull request by lnicola**
CC https://github.com/rust-lang/rust-analyzer/pull/14693#issuecomment-1529684094

### CODE REVIEW

**Comment by lnicola** [comment]
@Veykril can you give this a try (your old commit probably works too, though)?

**Comment by Veykril** [comment]
Checked it out on my machine, the perf decrease is also in the 10% for me so I guess its fine (maybe analysis overall gains from this elsewhere if we are lucky)

**Comment by lnicola** [comment]
It does show up in `analysis-stats`:

```
# baseline, 7d48bbadd449db111289d12db15d3a0dde1a9b14, best of 3
Database loaded:     506.62ms, 284minstr (metadata 300.22ms, 25minstr; build 102.00ms, 9815kinstr)
  crates: 44, mods: 918, decls: 19627, fns: 14681
Item Collection:     11.24s, 100ginstr
  exprs: 462280, ??ty: 33 (0%), ?ty: 129 (0%), !ty: 1                                                                                                                
  pats: 104232, ??ty: 4 (0%), ?ty: 11 (0%), !ty: 193
Inference:           38.46s, 280ginstr
Total:               49.70s, 381ginstr

# pr, best of 3
Database loaded:     509.21ms, 284minstr (metadata 301.47ms, 25minstr; build 105.61ms, 9815kinstr)
  crates: 44, mods: 918, decls: 19627, fns: 14681
Item Collection:     11.25s, 99ginstr
  exprs: 462280, ??ty: 33 (0%), ?ty: 129 (0%), !ty: 1                                                                                                                
  pats: 104232, ??ty: 4 (0%), ?ty: 11 (0%), !ty: 193
Inference:           41.70s, 296ginstr
Total:               52.96s, 395ginstr
```

**Comment by lnicola** [comment]
I think it might be a bit less than that because of noise. Another couple of runs:

```
# baseline
Total:               48.82s, 383ginstr
Total:               50.38s, 385ginstr
Total:               50.79s, 400ginstr

# pr
Total:               49.01s, 377ginstr
Total:               53.74s, 406ginstr
Total:               52.95s, 410ginstr
Total:               50.36s, 385ginstr
```

**Comment by Veykril** [comment]
> The instruction counts are all over the place, too.

That sounds terrible. But okay, then let's just try it with the commits.

**Comment by lnicola** [comment]
This would still be nice to have, but we'll have to fork or get someone to publish a new version before.

**Pull request closed without merging**
