### PR TITLE
Mega-sync from `rust-lang/rust`

### PR DESCRIPTION
**Pull request by fasterthanlime**
This essentially implements @oli-obk's suggestion here https://github.com/rust-lang/rust-analyzer/pull/13459#issuecomment-1297285607, with @eddyb's help.

This PR is equivalent to 14 syncs (back and forth) between `rust-lang/rust` and `rust-lang/rust-analyzer`.

Working from this list (from bottom to top):

```
(x) a2a1d9954 :arrow_up: rust-analyzer
(x) 79923c382 :arrow_up: rust-analyzer
(x) c60b1f641 :arrow_up: rust-analyzer
(x) 8807fc4cc :arrow_up: rust-analyzer
(x) a99a48e78 :arrow_up: rust-analyzer
(x) 4f55ebbd4 :arrow_up: rust-analyzer
(x) f5fde4df4 :arrow_up: rust-analyzer
(x) 459bbb422 :arrow_up: rust-analyzer
(x) 65e1dc4d9 :arrow_up: rust-analyzer
(x) 3e358a682 :arrow_up: rust-analyzer
(x) 31519bb39 :arrow_up: rust-analyzer
(x) 8231fee46 :arrow_up: rust-analyzer
(x) 22c8c9c40 :arrow_up: rust-analyzer
(x) 9d2cb42a4 :arrow_up: rust-analyzer
```

(This listed was assembled by doing a `git subtree push`, which made a branch, and looking at the new commits in that branch, picking only those that were `:arrow_up: rust-analyzer` commits)

We used the following commands to simulate merges in both directions:

```shell
TO_MERGE=22c8c9c40 # taken from the list above, bottom to top
git merge --no-edit --no-ff $TO_MERGE
git merge --no-edit --no-ff $(git -C ../rust log --pretty=format:'%cN | %s | %ad => %P' | rg -m1 -F "$(git show --no-patch --pretty=format:%ad $TO_MERGE)" | tee /dev/stderr | rg '.* => \S+ (\S+)$' --replace '$1')
```

We encountered no merge conflicts that Git wasn't able to solve by doing it this way.

Here's what the commit graph looks like (as shown in the Git Lens VSCode extension):

image

This PR closes #13459

## Does this unbreak `rust->ra` syncs?

Yes, here's how we tried:

In `rust-analyzer`:

  * check out `subtree-fix` (this PR's branch)
  * make a new branch off of it: `git checkout -b subtree-fix-merge-test`
  * simulate this PR getting merged with `git merge master`

In `rust`:

  * pull latest master
  * make a new branch: `git checkout -b test-change`
  * mess with rust-analyzer (I added a comment to `src/tools/rust-analyzer/Cargo.toml`)
  * commit
  * run `git subtree push -P src/tools/rust-analyzer ra-local final-sync` (this follows the [Clippy sync guide](https://doc.rust-lang.org/nightly/clippy/development/infrastructure/sync.html))

This created a `final-sync` branch in `rust-analyzer`.

In `rust-analyzer`:

  * `git merge --no-ff final-sync` (this follows the [Clippy sync guide](https://doc.rust-lang.org/nightly/clippy/development/infrastructure/sync.html))

Now `git log` in `rust-analyzer` shows this:

```
commit 460128387e46ddfc2b95921b2d7f6e913a3d2b9f (HEAD -> subtree-fix-merge-test)
Merge: 0513fc02a 9ce6a734f
Author: Amos Wenger <amoswenger@gmail.com>
Date:   Fri Nov 25 13:28:24 2022 +0100

    Merge branch 'final-sync' into subtree-fix-merge-test

commit 0513fc02a08ea9de952983624bd0a00e98044b36
Merge: 38c98d1ff 6918009fe
Author: Amos Wenger <amoswenger@gmail.com>
Date:   Fri Nov 25 13:28:02 2022 +0100

    Merge branch 'master' into subtree-fix-merge-test

commit 9ce6a734f37ef8e53689f1c6f427a9efafe846bd (final-sync)
Author: Amos Wenger <amoswenger@gmail.com>
Date:   Fri Nov 25 13:26:26 2022 +0100

    Mess with rust-analyzer just for fun
```

And `git diff 0513fc02a08ea9de952983624bd0a00e98044b36` shows this:

```patch
diff --git a/Cargo.toml b/Cargo.toml
index 286ef1e7d..c9e24cd19 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -32,3 +32,5 @@ debug = 0
 # ungrammar = { path = "../ungrammar" }
 
 # salsa = { path = "../salsa" }
+
+# lol, hi
```

## Does this unbreak `ra->rust` syncs?

Yes, here's how we tried.

From `rust`:

  * `git checkout -b sync-from-ra`
  * `git subtree pull -P src/tools/rust-analyzer ra-local subtree-fix-merge-test` (this is adapted from the [Clippy sync guide](https://doc.rust-lang.org/nightly/clippy/development/infrastructure/sync.html#performing-the-sync-from-clippy-to-rust-langrust), you would normally use `ra-upstream master` but we're simulating things here)

A commit editor pops up, there was no merge conflicts.

## How do we prevent this from happening again?

Like @bjorn3 said in https://github.com/rust-lang/rust-analyzer/pull/13459#issuecomment-1293587848

> Whenever syncing from rust-analyzer -> rust you have to immediately sync the merge commit from rust -> rust-analyzer to prevent merge conflicts in the future.

But if we get it wrong again, at least now we have a not-so-painful way to fix it.

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thank you very much for spending the time looking into this! (both of you :) )

r? @lnicola

**Comment by lnicola** [comment]
One issue I have with this is not being able to exclude commits. For example, I don't know if https://github.com/rust-lang/rust-analyzer/pull/13676/commits/3a1aa376c55cd070474a8488a2cf30a600beeb2f is something we want, but I understand how it happened downstream.

There's one more thing I want to try, i guess I'll be able to say more afterwards. But thanks for spending time on this.

**Comment by lcnr** [comment]
to set up maintainer notifications you can add yourself to the `triagebot.toml` file in the `rust` repo, e.g. https://github.com/rust-lang/rust/pull/104882

**Comment by eddyb** [comment]
> One issue I have with this is not being able to exclude commits. For example, I don't know if https://github.com/rust-lang/rust-analyzer/commit/3a1aa376c55cd070474a8488a2cf30a600beeb2f is something we want, but I understand how it happened downstream.

Please do not exclude commits, it's very important for the sync continuity that *you never edit/rebase/remove* commits generated by `git subtree`.

You can always do `git revert 3a1aa376c55cd070474a8488a2cf30a600beeb2f`, but not *remove* 3a1aa376c55cd070474a8488a2cf30a600beeb2f from the commit history, it's deterministically generated by `git subtree` every time you run `git subtree push` on the Rust side, and if you remove it when all the commits after it will change identity and make a horrible mess.

I would suggest swiftly merging this PR (after reverting whatever unwanted changes, tho if tests pass that can be done later too) to bring the two repos in sync once more, after which weekly syncs can resume as normal.

(The current state of the PR is **non-negociatiable** for allowing the subtree workflow, but we're talking about the commit graph here *not* the changes, which can be adjusted as-needed - e.g. adding revert commits to PR would result in the next RA -> `rust-lang/rust` sync to *also* include those new revert commits)

**Review by lnicola — APPROVED** [review]

**Pull request merged**
