### PR TITLE
Fix overlap deduping infinite loop

### PR DESCRIPTION
**Pull request by ComputerDruid**
Fixes: #14276

### CODE REVIEW

**Comment by ComputerDruid** [comment]
+cc @Veykril

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
🤦 thanks!
@bors r+

**Comment by lnicola** [comment]
changelog fix (first contribution) fix source root de-duping

**Comment by ComputerDruid** [comment]
> :facepalm: thanks!

I felt the same way when I finally saw the bug :heart:

**Pull request merged**
