### PR TITLE
feat: define problem matcher for panics in VS Code

### PR DESCRIPTION
**Pull request by matklad**
Now in VS Code "go to next error" (`F8`) will bring you to the source of a panic.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

**Comment by apollo-sturdy** [comment]
@matklad Is there a way to disable this? Since this update I am often confused to see red text in my file names and assume I have a compilation error, and instead just find that it is an error from a very old test run that has since been fixed. Is there already a way to clear these errors?

**Comment by matklad** [comment]
re-running the tests would clear the matched problem.

there’s upstream issue about dismissing obsolete matched problems: https://github.com/microsoft/vscode/issues/66982

**Comment by dnut** [comment]
> re-running the tests would clear the matched problem.

That's a very unsatisfying solution and not always practical.

> there’s upstream issue about dismissing obsolete matched problems: microsoft/vscode#66982

I can't believe this pr was merged without any kind of mechanism like this in place. And while the linked suggestion would improve things, this feature is still going to be very annoying. At the very least, the problem should disappear as soon as any code files are written to. The problem becomes stale as soon as you start typing, and it's pointless to keep it around any longer.

I think rust-analyzer would be better without this feature as it is right now. I've expressed some more detail at #14977

**Pull request merged**
