### PR TITLE
fix: don't use control flow when extracted fn contains tail expr of original fn

### LINKED ISSUE #10113: Extract to function assist leaves behind invalid code with if-let or match
```rust
struct Out;

fn a() -> Out {
    $0match Some(Out) {
        Some(v) => v,
        None => return Out,
    };

    Out$0
}
```

becomes

```rust
struct Out;

fn a() -> Out {
    match fun_name() {
        Ok(value) => value,
        Err(value) => return value,
    }
}

fn fun_name() -> Out {
    match Some(Out) {
        Some(v) => v,
        None => return Out,
    };
    Out
}
```

And if `Out` is replaced with `()`:

```rust
fn a() {
    if fun_name() {
        return;
    }
}

fn fun_name() {
    match Some(()) {
        Some(()) => (),
        None => return,
    }
    ()
}
```

### LINKED ISSUE #15061: Extract into function assist "unwraps" Result at the end of the function
Given the following function:

```rust
fn fallible() -> Result<(), ()> {
    if x {
        return Err(());
    }
    Ok(())
}
```

extracting the entire function body into a new function results in

```rust
fn fallible() -> Result<(), ()> {
    match fun_name() {
        Ok(value) => value,
        Err(value) => return value,
    }
}

fn fun_name() -> Result<(), ()> {
    if false {
        return Err(());
    }
    Ok(())
}
```

which is wrong because it results in a type mismatch between `fallible`s return type (`Result<(), ()>`) and the type of the match as well as the explicitly `return`ed type (just `()`).

**rust-analyzer version**: 0.4.1553-standalone

**rustc version**: 1.72.0-nightly (371994e0d 2023-06-13)

**relevant settings**:

```json
"rust-analyzer.cargo.features": "all",
"rust-analyzer.check.command": "clippy",
"rust-analyzer.diagnostics.experimental.enable": true,
"rust-analyzer.lens.implementations.enable": false,
"rust-analyzer.procMacro.ignored": {
    "async-trait": [
        "async_trait"
    ]
},
"rust-analyzer.rustfmt.overrideCommand": [
    "/home/jplatte/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustfmt",
    "--edition=2021"
],
```

### PR DESCRIPTION
**Pull request by lowr**
Fixes #10113
Fixes #15061

### CODE REVIEW

**Comment by DropDemBits** [comment]
Wondering if this fixes #10113 as well, since the function body there also looks similar.

**Comment by lowr** [comment]
It does! Thanks for noticing and sorry it took so long to fix this :pray:

**Comment by lowr** [comment]
I was going to refactor stuffs a bit because the code for this assist is quite messy, but I don't think I have time for this unfortunately. Marking as ready for review since the fix itself should be good to go.

**Pull request merged**
