### PR TITLE
Handle dev-dependency cycles

### PR DESCRIPTION
**Pull request by Veykril**
cc https://github.com/rust-lang/rust-analyzer/issues/14167

This should fix cycles errors mostly (it fixes the one on rome/tools at least, but not on rustc. Though  there it might just be because of rustc workspace being rustc workspace). Unfortunately this will effectively duplicate all crates currently, since if we want to be completely correct we'd need to set the test cfg for all dev dependencies and the transitive dependencies of those, something I worry we should try to avoid.

### CODE REVIEW

**Comment by davidbarsky** [comment]
> Unfortunately this will effectively duplicate all crates currently, since if we want to be completely correct we'd need to set the test cfg for all dev dependencies and the transitive dependencies of those, something I worry we should try to avoid.

Naive question: is this for only crates that are in the immediate workspace? naively, that feels like a reasonable and fine approach.

**Comment by Veykril** [comment]
The way its implemented right now is for all dev-dependencies (declared by workspace members, as dev-dependencies of libraries are irrelevant to the workspace) we will duplicate all their normal (non-build, non-dev) dependencies with the test flags. This would be completely correct as a dev depedency could re-export something from their normal dependencies that depends on the `test` cfg being set. but this also means as soon as you have a cycle (i.e a dev-dependency on a workspace member) you basically duplicate (almost) the entire crate graph. 

An alternative heuristic way would be to only duplicate dependencies in dev-dependency that point to workspace members and use the "non dev-version" for the rest. This will most likely cover the majority of cases.

**Comment by winksaville** [comment]
@Veykril pointed me at this issue from a [post I made at users.rust-lang](https://users.rust-lang.org/t/ra-reports-errors-but-compile-succeeds/92127). I've built RA from source and have it running on vscode and I'd like to see if this change fixes the problem I'm seeing. I'll give it a try if someone would kindly fix the merge conflicts :)

**Comment by Veykril** [comment]
Okay, I've changed it to now only duplicate workspace members. This cuts down the cyclic deps errors in the `rust-lang/rust` workspace from 50 to 23 (I believe the 23 come from the dependency on the rustc workspace itself which is already handled a bit incorrectly).

**Comment by Veykril** [comment]
Okay, actually we fortunately ignore anything but the first module we find for a file so most things should work if we prefer the duplicated crates. (symbol search and so on will still dupe, but I guess that is the price people will have to pay for now for adding a dev-dependency like that)

**Comment by winksaville** [comment]
FYI, I tested my [workspace](https://github.com/winksaville/exper_inter_process_channel) and there are no longer any errors. Txs!!!!

**Comment by chenyukang** [comment]
I verified it in my local, it works!!

**Comment by Veykril** [comment]
Something went terribly wrong with the rebase it seems

**Pull request merged**
