### PR TITLE
Change comparsion for checking if number is negative to include 128

### LINKED ISSUE #15096: wrong negative integer constant preview (on hover)
**rust-analyzer version**: 0.4.1558-standalone

**rustc version**: rustc 1.70.0 (90c541806 2023-05-31)

**relevant settings**: None

```rust
const A: i64 = i32::MIN as i64;
```

image

`A` is -2147483648 (i32::MIN), but then as a i64, but this does not change the value because i64 can hold all values i32 can

### PR DESCRIPTION
**Pull request by dfireBird**
The last byte in Little-Endian representation of negative integers start at 128 (Ox80) till 255 (OxFF). The comparison before the fix didn't check for 128 which made is_negative variable as false.

Potentially fixes #15096

### CODE REVIEW

**Comment by dfireBird** [comment]
+ @HKalbasi I created a PR for the fix.

**Comment by dfireBird** [comment]
Should I create a new test function or should I add the tests in `hir_ty::const_eval::tests::consts` test function?

**Comment by HKalbasi** [comment]
Both would work, do it as you see fit.

**Comment by dfireBird** [comment]
I added the tests in my system and it passed with fix. I temporarily reverted the see if the test fails or not but the test passed.
Then I checked the implementation of the `check_number` and saw it doesn't use the `pad16` function where the bug was present.

Should I change my tests to test the `HirDisplay` trait instead of using `check_number`? Can you help me on this?

**Comment by HKalbasi** [comment]
I think using `as` casts like the original example in #15096 and comparing large positive and negative numbers with themself and with zero would trigger the bug.

For checking the `HirDisplay` you can also add a test in `ide::hover::tests`, but keep the `as` cast and compare tests in `hir-ty`.

**Comment by dfireBird** [comment]
I wore more tests and using `as` cast like in original example triggered the bug and made the test fail. I also added some tests to the `hover` module as well.

P.S: Should I amend the two test commits into one, so they are organized and reduce the commit clutter?

**Comment by HKalbasi** [comment]
> P.S: Should I amend the two test commits into one, so they are organized and reduce the commit clutter?

Yes please, and then we can merge this I think.

**Comment by HKalbasi** [comment]
Thanks!
@bors r+

**Pull request merged**
