### PR TITLE
internal: fix a bunch of clippy lints

### PR DESCRIPTION
**Pull request by danieleades**
fixes a bunch of clippy lints for fun and profit

i'm aware of this repo's position on clippy. The changes are split into separate commits so they can be reviewed separately

### CODE REVIEW

**Comment by lnicola** [comment]
CC @nyurik looks like we got a bunch more [of these](https://github.com/rust-lang/rust-analyzer/pull/13860/commits/77051679d70ffb7421b1fb75402306a51c2337bd), even after #13835. I wonder if the auto-fix got smarter.

**Review by lnicola — APPROVED** [review]

**Comment by danieleades** [comment]
> CC @nyurik looks like we got a bunch more [of these](https://github.com/rust-lang/rust-analyzer/pull/13860/commits/77051679d70ffb7421b1fb75402306a51c2337bd), even after #13835. I wonder if the auto-fix got smarter.

This repo's clippy policy means that there are a bunch of clippy lints being triggered. Clippy only reports a small number of hard errors before bailing early. If you fix the hard errors, clippy will report more warnings

**Comment by lnicola** [comment]
> Clippy only reports a small number of hard errors before bailing early.

Ah, I didn't know that. So if you run `cargo clippy --fix -- -A clippy::all -W clippy::uninlined_format_args` multiple times, it will keep fixing things until there's no more `uninlined_format_args`? Interesting.

**Comment by lnicola** [comment]
Regarding clippy in general, if someone finds a set of "good" lints (without false positives or of questionable benefit), they can be added [here](https://github.com/rust-lang/rust-analyzer/blob/master/.cargo/config.toml) and we'll be open to fixing them.

**Pull request merged**
