### PR TITLE
feat: Make "inline type alias" work for `Self`

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes https://github.com/rust-lang/rust-analyzer/issues/12109

### CODE REVIEW

**Comment by sancho20021** [comment]
Hi @jonas-schievink . In this Fixme:
https://github.com/rust-lang/rust-analyzer/blob/3eb340fa4d9872634f4b36785031827ab3ebc0f2/crates/ide-assists/src/handlers/inline_type_alias.rs#L53

What do you mean by ADT, enums? Could you please provide an example where it should work but doesn't.

**Comment by jonas-schievink** [comment]
I think that was referring to something like this:

```rust
struct S {
    next: Option<Box<Self$0>>,
}
```

Currently "Inline type alias" doesn't work there.

**Pull request merged**
