### PR TITLE
fix: Extract Function misses locals used in closures

### LINKED ISSUE #12705: Extract Function assist misses parameters for locals passed to closures
**rust-analyzer version**: rust-analyzer version: 0.0.0 (75b22326d 2022-07-03)

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: N/A

When using the Extract Function assist on code that includes a closure, closed-over locals from the body are not added to the param list for the new function.

```rust
fn parent(factor: i32) {
    let v = vec![1, 2, 3];

    $0v.iter().map(|it| it * factor);$0
}
```
->
```rust
fn parent(factor: i32) {
    let v = vec![1, 2, 3];

    fun_name(v);
}

fn fun_name(v: Vec<i32>) {
    v.iter().map(|it| it * factor);
}
```

instead of 

```rust

fn parent(factor: i32) {
    let v = vec![1, 2, 3];

    fun_name(v, factor);
}

fn fun_name(v: Vec<i32>, factor: i32) {
    v.iter().map(|it| it * factor);
}
```

### PR DESCRIPTION
**Pull request by DorianListens**
This change fixes #12705.

In `FunctionBody::analyze`, we need to search any `ClosureExpr`s we encounter
for any `NameRef`s, to ensure they aren't missed.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks!

@bors r+

**Comment by jonas-schievink** [comment]
Oh it's "delegate" on homu

@bors delegate+

**Comment by DorianListens** [comment]
Thanks @jonas-schievink !

@bors r+

**Pull request merged**
