### PR TITLE
Suggest struct when completing enum

### LINKED ISSUE #13107: Suggest structure type in enum variant
Lets say we have 

```
pub struct YoloVariant {}

pub enum HH {
    Yolo(YoloVariant),
}

fn brr() {
    let t = HH::Yolo(_|_);
}
```

Expected to have `YoloVariant` in suggestions.

### PR DESCRIPTION
**Pull request by Austaras**
closes #13107

### CODE REVIEW

**Comment by flodiebold** [comment]
Hmm I'm not sure this is going in the right direction, I don't think this needed a completely new completion, just a fix to the code that determines the expected type [here](https://github.com/rust-lang/rust-analyzer/blob/f02cd0a41d7381b1ef454b0141adacc188d3eee8/crates/ide-completion/src/context/analysis.rs#L165)?

**Comment by Austaras** [comment]
But complete enum variant with struct should be another entry?

**Comment by flodiebold** [comment]
The struct completion will show up as another entry when we have the correct expected type, like in this example:
```rust
pub struct YoloVariant {}

fn yolo(y: YoloVariant) {}

fn brr() {
    let t = yolo(<|>);
}
```
For a function call like that, we correctly determine the expected type, so we show a `YoloVariant {}` completion at the top in addition to the standard `YoloVariant` entry. That's what's missing for the enum variant.

**Comment by Austaras** [comment]
Whoops, seems like I misread the entire issue. I thought it's for
```rs
struct Y {}
enum Y {
  y(Y)
}

fn brr() {
    let t = Y::<|>;
}
```
rust analyzer would emit
```
y()
y(Y {})
```
I would rewrite this when I have time.

**Pull request merged**
