### PR TITLE
Implement lsp extension for cancelling running flychecks

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/4828

### CODE REVIEW

**Comment by RalfJung** [comment]
This is awesome. :)

How do I trigger cancelling the running checks from the UI?

**Comment by Veykril** [comment]
For VSCode, without any setup you'd need to bring up the command bar(? not sure if thats the name) via <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> and then type out `Cancel running flychecks` until you find that and invoke it.

The other way is to set up a keybinding to invoke the `rust-analyzer.cancelFlycheck` command

**Comment by Veykril** [comment]
I wanted to make the small `cargo check` spinner in the status bar clickable but that thing is actually not managed by the r-a client at all so we don't have control over that 🙄 Will have to look into other options there

**Pull request merged**
