### PR TITLE
Fix typo in type name

### PR DESCRIPTION
**Pull request by Wilfred**

### CODE REVIEW

**Comment by lnicola** [comment]
I think this is a bit obscure since the code got rewritten, but `Jod` is correct. It stands for "join on drop", as in https://docs.rs/jod-thread/.

**Comment by Veykril** [comment]
That is indeed intentional

**Comment by Wilfred** [comment]
Fair enough! I saw that the group value was called a `job` and jumped to conclusions :)

I guess we could rename it to Tod (terminate on drop) as it's not joining, or I could put up a PR for a doc comment if you think it's worthwhile?

**Comment by lnicola** [comment]
> I guess we could rename it to Tod (terminate on drop) as it's not joining

That would be a good inside joke given the current proportion of German-speaking RA developers.

**Pull request closed without merging**
