### PR TITLE
Update perf-event to 0.4.8

### PR DESCRIPTION
**Pull request by gigaroby**

### CODE REVIEW

**Comment by lnicola** [comment]
Thanks, any particular reason for this?

**Comment by gigaroby** [comment]
Just convenience for our internal process, it's easier to import the latest version of dependencies. If this kind of version bump is not appreciated, I'm happy to undo it.

**Comment by lnicola** [comment]
No, it's fine, but I think we lag on others too, so I was wondering if there's anything in particular about this one.

**Comment by Veykril** [comment]
Looks like we can't bump it? (given CI)

**Pull request closed without merging**
