### PR TITLE
feat: Add `unqualify_method_call` assist

### PR DESCRIPTION
**Pull request by WaffleLapkin**
...which is the inverse of `qualify_method_call` assist.

Peek 2022-12-22 22-47

Optional future work:
- import the trait if needed
- remove excess references when auto-ref is possible

### CODE REVIEW

**Comment by flodiebold** [comment]
I think the acronym "UFCS" is a bit unfriendly, maybe something like "Convert to `.add` method call"? (Also btw, why is "Qualify method call" under "Inline"?)

**Comment by Veykril** [comment]
+1 to `UFCS` being a bad choice for the user visible text

> Also btw, why is "Qualify method call" under "Inline"?

Probably because both target the same range and our assists are ordered alphabetically by default (with a few exceptions, where this would probably be a good choice to do so as well)

**Comment by flodiebold** [comment]
> Probably because both target the same range and our assists are ordered alphabetically by default (with a few exceptions, where this would probably be a good choice to do so as well)

I didn't mean the order, rather that it's under the `Inline...` group (whereas the new assist is `Rewrite...`) :sweat_smile:

**Pull request merged**
