### PR TITLE
fix: Fix panic on unaligned packed attribute

### LINKED ISSUE #16284: ice: repr packed not a power of 2
```rust
#[repr(packed(5))]
struct S 
```

`rust-analyzer highlight  < a.rs`
```
thread 'main' panicked at crates/hir-def/src/data/adt.rs:131:56:
called `Result::unwrap()` on an `Err` value: `5` is not a power of 2
stack backtrace:
   0: rust_begin_unwind
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/result.rs:1649:5
   3: hir_def::data::adt::repr_from_value
   4: <hir_def::db::StructDataWithDiagnosticsQuery as salsa::plumbing::QueryFunction>::execute
   5: <salsa::derived::slot::Slot<hir_def::db::StructDataWithDiagnosticsQuery, salsa::derived::AlwaysMemoizeValue>>::execute
   6: <_ as hir_def::db::DefDatabase>::struct_data_with_diagnostics::__shim
   7: <ide_db::RootDatabase as hir_def::db::DefDatabase>::struct_data_with_diagnostics
   8: <salsa::derived::slot::Slot<hir_def::db::StructDataQuery, salsa::derived::AlwaysMemoizeValue>>::execute
   9: <_ as hir_def::db::DefDatabase>::struct_data::__shim
  10: <hir::Struct as hir::HasVisibility>::visibility
  11: <hir::Adt as hir::HasVisibility>::visibility
  12: <ide_db::defs::Definition>::visibility
  13: ide::syntax_highlighting::highlight::highlight_def
  14: ide::syntax_highlighting::highlight
  15: <ide::Analysis>::highlight_as_html
  16: <rust_analyzer::cli::flags::Highlight>::run
  17: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`rust-analyzer 1.77.0-nightly (595bc6f 2024-01-05)`

### PR DESCRIPTION
**Pull request by lnicola**
Closes #16284

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
That was fast :D <3

**Comment by lnicola** [comment]
@Veykril you wouldn't happen to know a good place to add a test for this, would you? Just so I don't put it under `crates/ide/src/syntax_highlighting/tests.rs` :sweat_smile:.

**Comment by lnicola** [comment]
@matthiaskrgr how did you find these? Fuzzer?

**Comment by matthiaskrgr** [comment]
So far I checked matthiaskrgr/glacier2 , rust-lang/rust  with, very simplified 
```
for file in all_the_files {
rust-analyzer highlight < file.rs  | grep panic
}
```

Right now I am checking the entire history of rust-lang/rust (4.5 million files, several tens of gigabyte of code) ^^
Already 26% through.
I can do actual file-based fuzzing and maybe `analysis-stats` or `diagnostics` later which will require a bit more coding on my side.

**Comment by lnicola** [comment]
I see. Just so you know, we already have a parset fuzzing harness set up, which we never run (for good reasons).

**Comment by Veykril** [comment]
Uh, the layout test in `hir-ty/src/layout` probably

**Comment by matthiaskrgr** [comment]
>I see. Just so you know, we already have a parset fuzzing harness set up, which we never run (for good reasons).

I have added another algo to search for files that pass rustc compilation but fail `rust-analyzer diagnostics` which should yield more interesting results.

**Pull request merged**
