### PR TITLE
Update offset intrinsic to match 1.72

### LINKED ISSUE #15498: MIR eval got very slow between rustc 1.72.0-nightly (8c74a5d27 2023-06-14) and rustc 1.72.0-nightly (114fb86ca 2023-06-15)
https://github.com/rust-lang/rust-analyzer/pull/15494#issuecomment-1687429493

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #15498

### CODE REVIEW

**Comment by lnicola** [comment]
Needs a `cargo fmt` on 1.72.

**Comment by lnicola** [comment]
What happens on pre-1.72?

**Comment by HKalbasi** [comment]
> What happens on pre-1.72?

It will return `offset generic arg is not provided`, then falls back to the non `Debug` rendering of constants.

**Comment by lnicola** [comment]
Filed #15513 for the CI failure.

**Comment by lnicola** [comment]
Oh, right, can you include the commits from #15513?

**Pull request merged**
