### PR TITLE
Restart server automatically on settings changes

### LINKED ISSUE #12476: Auto restart server on settings changes
Following from https://github.com/rust-lang/rust-analyzer/pull/12471, would it be possible to restart the server automatically? Previously this would have been very disruptive as the whole window would reload, but now I think it should be fine. Perhaps this could be made configurable behind a setting?

### PR DESCRIPTION
**Pull request by hasali19**
Closes #12476 

I think this works quite well, but if you think it would be better to put it behind a setting I can do that.

### CODE REVIEW

**Comment by bjorn3** [comment]
If I'm editing the preferences I wouldn't want rust-analyzer to restart every time I make a small change, only once I am done. Doing otherwise is a waste of resources and may make vscode unresponsive for a while on weak systems.

**Comment by hasali19** [comment]
It only reloads when you actually save the settings, though if you save multiple times while editing that seems reasonable I guess. This would be quite convenient in my case as I frequently need to switch the build target for one of my projects - should I make it a setting instead?

**Comment by bjorn3** [comment]
A setting for this would be nice indeed.

**Comment by hasali19** [comment]
Great, I've added `rust-analyzer.restartServerOnConfigChange`.

**Pull request merged**
