### PR TITLE
fix: #12267  type-mismatch when using equals w/ a trait bound

### LINKED ISSUE #12267: type-mismatch when using equals w/ a trait bound on an associated type
i really don't know a better way to title this, but here's a minimization of what I encountered just now:

```rust
fn repro<T>(t: T) -> bool
where
    T: Request,
    T::Output: Convertable,
{
    let a = execute(&t).convert();
    let b = execute(&t).convert();

    a == b
    //   ^ expected <T as Request>::Output, found <<T as Request>::Output as Convertable>::Output rust-analyzer[type-mismatch]
}

fn execute<T>(t: &T) -> T::Output
where
    T: Request,
{
    todo!()
}

trait Convertable {
    type Output: PartialEq;

    fn convert(self) -> Self::Output;
}

trait Request {
    type Output;
}

```

rust-analyzer version: 94fa8a653 2022-05-12 nightly
rustc 1.60.0 (7737e0b5c 2022-04-04)

### PR DESCRIPTION
**Pull request by bitgaoshu**

### CODE REVIEW

**Comment by bitgaoshu** [comment]
fix https://github.com/rust-lang/rust-analyzer/issues/12267

**Comment by bitgaoshu** [comment]
can review this?

**Comment by flodiebold** [comment]
Seems to make sense. For safety, could you check for any changes to the output of `rust-analyzer analysis-stats .` at least on the rust-analyzer repository, maybe also some other repos?

**Comment by bitgaoshu** [comment]
like this?

1. run under r-a
```
[~/logs]$ diff nopatch_e  patch_e
1,6c1,6
< Database loaded:     17.40s (metadata 1.98s; build 12.28s)
<   crates: 41, mods: 891, decls: 21081, fns: 15746
< Item Collection:     23.50s
<   exprs: 435989, ??ty: 336 (0%), ?ty: 226 (0%), !ty: 4
< Inference:           107.19s
< Total:               130.69s
---
> Database loaded:     15.21s (metadata 1.77s; build 11.53s)
>   crates: 41, mods: 891, decls: 21082, fns: 15747
> Item Collection:     23.08s
>   exprs: 436000, ??ty: 336 (0%), ?ty: 226 (0%), !ty: 4
> Inference:           109.61s
> Total:               132.69s
```

2. run under Tokio
```
[~/logs]$ diff tokio_nopatch_e tokio_patch_e
7c7
< Database loaded:     13.31s (metadata 1.01s; build 11.25s)
---
> Database loaded:     5.77s (metadata 2.32s; build 763.54ms)
9c9
< Item Collection:     19.20s
---
> Item Collection:     18.82s
11,12c11,12
< Inference:           44.43s
< Total:               63.62s
---
> Inference:           43.95s
> Total:               62.77s
```

**Comment by flodiebold** [comment]
That looks good!

@bors r+

**Pull request merged**
