### PR TITLE
minor: rename

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
Not sure what is happeneing here with CI...

**Comment by jonas-schievink** [comment]
```
error[E0432]: unresolved import `crate::thread_pool`
  --> crates/rust-analyzer/src/global_state.rs:29:5
   |
29 |     thread_pool::TaskPool,
   |     ^^^^^^^^^^^ could not find `thread_pool` in the crate root
```

Not sure where the closure errors are coming from though. Might be a rustc bug. Aren't we using 2021 edition already?

**Comment by jonas-schievink** [comment]
(also if you used rename symbol to do this rename it looks like we have some bugs to fix there :sweat_smile:)

**Comment by matklad** [comment]
I think I did use rename symbol, and I think it did actually rename that import... So perhaps VS Code just failed to persist that to disk? 

@bors r+

**Pull request merged**
