### PR TITLE
Update dependencies for editor/code

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
This updates dependencies except `@types/node`.

### CODE REVIEW

**Comment by lnicola** [comment]
> This updates dependencies except @types/node and @types/vscode

I think we can bump Code too to 1.78.

**Comment by lnicola** [comment]
We nominally support the latest two versions, it's probably fine to do it here. And I don't think the supported version actually changes unless you also bump `engine` somewhere else in the same file.

**Comment by tetsuharuohzeki** [comment]
> We nominally support the latest two versions, it's probably fine to do it here. And I don't think the supported version actually changes unless you also bump `engine` somewhere else in the same file.

Okay, I update my changeset.

**Review by lnicola — APPROVED** [review]
That diffstat is certainly intriguing. I think we should merge this sooner rather than later, so we have time to spot any issues before the next release.

**Comment by tetsuharuohzeki** [comment]
@lnicola CI has passed.

**Pull request merged**
