### PR TITLE
fix: complete non-std enum at the start of `use` completions

### PR DESCRIPTION
**Pull request by yue4u**
close: #12421

### CODE REVIEW

**Comment by jhgg** [comment]
QQ: Should this complete to `FooEnum::*`?

**Comment by yue4u** [comment]
> QQ: Should this complete to `FooEnum::*`?

In my own option I think the only name is enough since `use FooEnum::$0` is already supported. Not sure which is more common when comparing using a single variant to using a whole enum.

**Comment by yue4u** [comment]
Oh If you mean showing `FooEnum::` the problem is similar as you have to delete `::` if you want the name. Maybe showing both `FooEnum` and `FooEnum::` is also acceptable only a bit more noisy?

**Pull request merged**
