### PR TITLE
Find original ast node before compute ref match

### PR DESCRIPTION
**Pull request by hi-rustin**
ref https://github.com/rust-lang/rust-analyzer/issues/12717

### CODE REVIEW

**Comment by Veykril** [comment]
The tests should succeed once https://github.com/rust-lang/rust-analyzer/pull/12886 is merged and this PR is rebased on top

**Comment by hi-rustin** [comment]
> The tests should succeed once #12886 is merged and this PR is rebased on top

Rebased. But still does not work. Did I miss using the API?

**Comment by Veykril** [comment]
Hmm, will take another look at this later

**Comment by Veykril** [comment]
Ah right, the path is from the fake file so we can't do that for the path here... hmm. Can you remove the ones that try to do this for paths, and only leave the receiver ones? Those should work, the path ones will be a bit more tricky to fix. will have to think about those

**Comment by hi-rustin** [comment]
> Ah right, the path is from the fake file so we can't do that for the path here... hmm. Can you remove the ones that try to do this for paths, and only leave the receiver ones? Those should work, the path ones will be a bit more tricky to fix. will have to think about those

Done. 
Thanks for your review!  💚 💙 💜 💛 ❤️

**Pull request merged**
