### PR TITLE
Remove hir::Expr::MacroStmts

### PR DESCRIPTION
**Pull request by Veykril**
This hir expression isn't needed and only existed as it was simpler to
deal with at first as it gave us a direct mapping for the ast version of
the same construct. This PR removes it, properly handling the statements
that are introduced by macro call expressions.

### CODE REVIEW

**Comment by Veykril** [comment]
cc https://github.com/rust-lang/rust-analyzer/pull/13027, let's see if this brings the sourcegen unknown types back down 😬

**Comment by jonas-schievink** [comment]
Very nice, I was meaning to do this

**Comment by Veykril** [comment]
🎉
image

**Pull request merged**
