### PR TITLE
feat: Allow viewing the full compiler diagnostic in a readonly textview

### PR DESCRIPTION
**Pull request by Veykril**
Code_y1qrash9gg

Also adds a VSCode only config that replaces the split diagnostic message with the first relevant part of the diagnostic output

Code_7k4qsMkx5e

This only affects diagnostics generated by primary spans and has no effect on other clients than VSCode.

Fixes https://github.com/rust-lang/rust-analyzer/issues/13574

### CODE REVIEW

**Comment by bjorn3** [comment]
If you hover over an error there is a "View Problem" button, right? Can you put the full diagnostic in the peek it shows when pressing this button?

image

**Comment by Veykril** [comment]
That is just VSCode rendering the diagnostic messages you see on hover in the red box, not much we can do there

**Comment by bjorn3** [comment]
Really, they don't allow putting a full diagnostic in there? Why do they even have that button then?

**Comment by Veykril** [comment]
VSCode basically allows you to do nothing with diagnostics :)

**Comment by bjorn3** [comment]
:sob:

**Comment by ChayimFriedman2** [comment]
We need to make it so when people copy the diagnostic it'll copy the full diagnostic (don't think we can do that, unfortunately).

**Comment by Veykril** [comment]
What exactly do you mean with that?

**Comment by ChayimFriedman2** [comment]
People many times ask for help with the truncated rust-analyzer diagnostic. It would be nice if copying it would result in the full diagnostic being copied.

**Pull request merged**
