### PR TITLE
fix: Properly prevent mir building with unknown types present

### PR DESCRIPTION
**Pull request by Veykril**

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
Preventing building of *all* MIR seems too much, we have some IDE features relying on MIR and it'll be a shame if they won't work (or work incorrectly) for incomplete code.

Instead, we should be more relaxed in MIR lowering, and allow improper HIR in it.

**Comment by Veykril** [comment]
> Instead, we should be more relaxed in MIR lowering, and allow improper HIR in it.

I don't disagree but I've been unable to locate the exact cause of this after a couple tries by now unfortunately.

**Pull request merged**
