### PR TITLE
Use debug impl in rendering const eval result

### LINKED ISSUE #15188: Hover on constants should render the display/debug impl if available
Might be a crazy idea but I'll take the bitflags crate as an example here (although we fail to calculate the layout for it in const eval due to the projection used I believe, pasting the expansion and fixing that up makes it work):
```rs
bitflags::bitflags! {
    #[derive(Default, Debug, Clone, Copy)]
    pub(crate) struct TypeVariableFlags: u8 {
        const DIVERGING = 1 << 0;
        const INTEGER = 1 << 1;
        const FLOAT = 1 << 2;
        const FOO = TypeVariableFlags::FLOAT.bits() | TypeVariableFlags::INTEGER.bits();
    }
}
```

Hovering `FOO` renders (again `<layout-error>` currently) the following:
```rs
hir_ty::infer::unify::x
const Foo: TypeVariableFlags = TypeVariableFlags(InternalBitFlags(3))
```
which is obviously not that useful, meanwhile the debug implementation would render as:
```
TypeVariableFlags(INTEGER | FLOAT)
```

Noticed this in a project of mine that works with bitflags where our hover is practically useless 
image

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #15188

### CODE REVIEW

**Comment by Veykril** [comment]
Fwiw, this fails on latest nightly in general. (And on stable my code that spawned this idea also fails on a specific debug impl, though I guess that is to be expected).

**Comment by HKalbasi** [comment]
> Fwiw, this fails on latest nightly in general.

That's bad. I tried to make it working. Will look at it.

> also fails on a specific debug impl

I may be able to fix it if I know the problem. You can see why it fails by using the `Interpret Function` command on a function containing `format!("{:?}", C)`.

**Comment by Veykril** [comment]
```text
Mir eval error:
In function f (FunctionId(19684))
In function format (FunctionId(18759))
In ClosureId(39)
file://C:\Users\lukas\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs#1193:20
In function format (FunctionId(18759))
In function format_inner (FunctionId(55204))
file://C:\Users\lukas\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\fmt.rs#612:8
In function write_fmt (FunctionId(29913))
In function write (FunctionId(12864))
file://C:\Users\lukas\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\fmt\mod.rs#1244:10
In function fmt (FunctionId(19811))
file://c:\workspace\rust\glaive\crates\parser\src\token_set.rs#61:20
In function next (FunctionId(28724))
In function spec_next (FunctionId(28712))
file://C:\Users\lukas\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\iter\range.rs#539:38
In function replace (FunctionId(12702))
NotSupported("unknown intrinsic read_via_copy")
```

Clearly something is going very much wrong here. The problem manifest iwth the following debu impl
```rs
impl fmt::Debug for TokenSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TokenSet(")?;
        let mut first = true;
        for kind in 0..SyntaxKind::LAST_TOKEN.to_raw().0 {
            // let kind = SyntaxKind::from_raw(rowan::RawSyntaxKind(kind));
            // if self.contains(kind) {
            //     if first {
            //         first = false;
            //     } else {
            //         f.write_str(" | ")?;
            //     }
            //     write!(f, "{:?}", kind)?;
            // }
        }
        write!(f, ")")?;
        Ok(())
    }
}
```
Commenting out the loop makes it pass. Seems like just havin a `for kind in 0..10 {}` fails with the intrinsic

**Comment by HKalbasi** [comment]
Ah, I'm using a patched std from 1.69, and this `read_via_copy` stuff is added in 1.70 so doesn't exists in my world. I will try to bump my std to 1.70 in following days. `read_via_copy` on its own is very trivial, but it might be tip of the iceberg.

**Comment by HKalbasi** [comment]
It seems the only problem was `read_via_copy` and after #15244 mir interpreter should work with its full power on stable, so you can try again. On nightly it seems there is a more serious problem, something in the allocator is broken, so vector doesn't work, string which is just a `Vec<u8>` doesn't work, and so `std::fmt::format` doesn't work. Will look at it.

**Pull request merged**
