### PR TITLE
Bring the version command output in line with other rust tools

### PR DESCRIPTION
**Pull request by Veykril**
Inspired by how cargo handles it
Fixes https://github.com/rust-lang/rust-analyzer/issues/12280
image

### CODE REVIEW

**Comment by Veykril** [comment]
Not sure how rustbuild works though so @cuviper, you should probably have a look at this as well since you opened the issue.

This also needs an adjustment for the submodule building the rust repo I imagine since this changes the env vars.

**Comment by cuviper** [comment]
Looks good to me! Those `CFG_RELEASE*` envs are set by rustbuild for all `ToolBuild` steps, so I think that will be fine. I think this information will also be useful for RA maintainers to see where bug reports are coming from. (cc #12432)

Not sure what you mean about the submodule -- build scripts should run in your source dir, so I think git will see the right thing.

**Pull request merged**
