### PR TITLE
Add str_ref_to_string fix

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/rust-lang/rust-analyzer/issues/11383
When type mismatch is `&str` -> `String` try to fix it.

### CODE REVIEW

**Comment by hi-rustin** [comment]
@Veykril 
Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Comment by Veykril** [comment]
I'm a bit busy atm, will take a look when I find the time (unless someone beats me to it)

**Comment by Veykril** [comment]
We probably want this to be a bit more generally applicable if possible (and certainly not just text based by checking the types names) but in this instance this seems fine for now I think. We can figure out the better way afterwards since this is self-contained.

Thanks
@bors r+

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/179480044-bc6ff0a1-3ea3-45bc-bbf6-23181957ab3e.mp4

**Comment by rben01** [comment]
I feel like `to_owned` and `into` would be better options than `to_string` here. `to_string` means, essentially, "convert to the String that Display::fmt would give me". For `&str`, this happens to be the same as converting to an owned String, but that seems like a happy coincidence. `to_owned` and `into` are more explicit about the nature of the transformation taking place.

**Pull request merged**
