### PR TITLE
internal: Include toml files in the vfs

### LINKED ISSUE #15753: flycheck 0: File with cargo diagnostic not found in VFS: file not found: clippy.toml
```
[ERROR rust_analyzer::main_loop] flycheck 0: File with cargo diagnostic not found in VFS: file not found: d:\beam-pls\clippy.toml
```

VSCode about
```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**rust-analyzer version**: rust-analyzer version: 0.3.1689-standalone (b1f89a84a 2023-10-06)

**rustc version**: rustc 1.73.0 (cc66ad468 2023-10-03)

**relevant settings**:

clippy.toml
```toml
new_without_default = false
```

settings.json (project dir)
```json
{
	"editor.formatOnSave": true,
	"rust-analyzer.check.allTargets": false,
	"rust-analyzer.check.extraArgs": [
		"--all"
	],
	"rust-analyzer.showUnlinkedFileNotification": false,
	"rust-analyzer.check.command": "clippy"
}
```

settings.json (user preferences)
```json
{
    "rust-analyzer.showUnlinkedFileNotification": false,
    "rust-analyzer.checkOnSave.command": "clippy",
    "rust-analyzer.trace.server": "messages",
    "rust-analyzer.checkOnSave.allTargets": false
}
```

### PR DESCRIPTION
**Pull request by lnicola**
Closes #15753

### CODE REVIEW

**Comment by Veykril** [comment]
I think it'd be fine to just include `rust-analyzer.toml`, `Cargo.toml` and `clippy.toml` (and `.` prefixed variants as well I guess? for clippy and r-a)

**Comment by Veykril** [comment]
Assuming we can do that easily, I don't remember how this stuff works. Otherwise this seems fine to me as well

**Comment by lnicola** [comment]
IIRC I looked into it and it didn't seem trivial. It even took me a lot of time to figure out how we load `.rs` files.

I think `Cargo.toml` and `Cargo.lock` are loaded with the workspace, while the code here filters by extension.

**Comment by Veykril** [comment]
Does not surprise me, then let's keep it this way for now
@bors r+

**Pull request merged**
