### PR TITLE
docs: document a few node types

### PR DESCRIPTION
**Pull request by dev-ardi**

### CODE REVIEW

**Comment by lnicola** [comment]
Not to spoil your fun, but that file is generated automatically and shouldn't be edited.

**Comment by dev-ardi** [comment]
Uh... Where do the actual definitions come from?

**Comment by lnicola** [comment]
https://github.com/rust-lang/rust-analyzer/blob/master/crates/syntax/rust.ungram

**Comment by dev-ardi** [comment]
Uh so it's impossible to document them?

**Comment by lnicola** [comment]
`ungram` could parse [the comments](https://github.com/rust-lang/rust-analyzer/blob/master/crates/syntax/rust.ungram#L229-L231) and emit them as rustdoc.

**Comment by dev-ardi** [comment]
How hard would that be to achieve?

**Pull request closed without merging**
