### PR TITLE
Fix markdown removal in hover handling whitespace weirdly

### PR DESCRIPTION
**Pull request by Veykril**
Fixes https://github.com/rust-lang/rust-analyzer/issues/10028

### CODE REVIEW

**Comment by sclu1034** [comment]
As mentioned in #10028, line wraps are also messed up. kak-lsp has implemented Markdown by now, so I have nothing set up to test this with right now, but looking at the code, I don't see anything changed in this regard.
Specifically, soft wraps (`Event::SoftBreak`) probably shouldn't be turned into hard wraps (by inserting `\n`), as rust-analyzer cannot make assumptions about how the text will eventually be rendered.

E.g. the original Markdown might use soft wraps to limit the line length to 100 columns, but when the client only has 80 columns to render the result, you'd get breaks mid-screen:

```ini
# soft wraps at 100 columns
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa
nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi
cupiditate. Voluptatum ducimus voluptates voluptas?
# turned into hard breaks and rendered at 80 columns
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis
exercitationem culpa
nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus
asperiores quasi
cupiditate. Voluptatum ducimus voluptates voluptas?
```

This would also bring it in line with how Markdown is rendered into HTML:

> A regular line ending (not in a code span or HTML tag) that is not preceded by two or more spaces or a backslash is parsed as a softbreak.
> \- https://spec.commonmark.org/0.30/#soft-line-breaks

Browsers then turn a softbreak into a single space character:

```ini
# soft wraps at 100 columns
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis exercitationem culpa
nesciunt nihil aut nostrum explicabo reprehenderit optio amet ab temporibus asperiores quasi
cupiditate. Voluptatum ducimus voluptates voluptas?
# turned into spaces and rendered at 80 columns
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi non quis
exercitationem culpa nesciunt nihil aut nostrum explicabo reprehenderit optio
amet ab temporibus asperiores quasi cupiditate. Voluptatum ducimus voluptates
voluptas?
```

**Comment by Veykril** [comment]
Hm, so what should we do with softbreaks? Just ignore them?

**Comment by sclu1034** [comment]
I'd turn them into spaces, like browsers do in HTML.

**Pull request merged**
