### PR TITLE
fix: Fix proc-macro-server incorrectly stripping delimiters

### PR DESCRIPTION
**Pull request by Veykril**
🙄

### CODE REVIEW

**Comment by Veykril** [comment]
We should definitely look into running the proc-macro-server tests on a nightly toolchain on CI I think
@bors r+

**Comment by Veykril** [comment]
@lnicola do you wanna try to do another subtree after this (or should we merge the other PRs that are ready to be merged first as well)?

**Comment by lnicola** [comment]
I was just asking that. Let's merge the PRs that are ready and hope for the best. 😅

**Comment by Veykril** [comment]
Actually let's only merge https://github.com/rust-lang/rust-analyzer/pull/14138 quickly, the other ones touch things I'd rather not have break and be shipped on rustup right after

**Pull request merged**
