### PR TITLE
fix: Pass flycheck extra args when running build scripts

### LINKED ISSUE #14315: Lsp not working in cargo check -r
I recently updated my ra's config to run ** cargo check -r ** insted of cargo check (debug mode) 
Because i usually run my projects in release mode.

I use nvim-lspconfig and i keymapped "K" to show the hover (Just like in vscode). But it show this error 
`**edit: 
I just got to know that lol the lsp is only working. Idk what is this But i think that for ra to get compleition , code action and hover working it needs to get a debug build**`
``` man.lua: "no manual entry for PathBuf"``` 
when i try to get hover for PathBuf.

Is this a bug or a release issue idk. Btw thanks for help and also for build such a great software

minimal config 
```
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'rust_analyzer'
local cmd = {
	["rust-analyzer"] = {
          check = {
            extraArgs = {"-r"},
          },
        },
      },
 -- needed for elixirls, lua_ls, omnisharp
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### PR DESCRIPTION
**Pull request by lnicola**
Closes #14315

Not sure if we want to do it like this or to add an extra config key, though.

### CODE REVIEW

**Comment by ayush-india** [comment]
Waiting for the check to be completed
Thanks a lot mate

**Comment by lnicola** [comment]
It's waiting for a review, I don't know if this is the best approach.

**Comment by ayush-india** [comment]
Does not matter to me i am anyway going to complie it from src and use it

**Comment by ayush-india** [comment]
Can i we the code of this pull request

**Comment by Veykril** [comment]
We should add a separate key for that instead and have the check one inherit it like we do with the other configs for these imo

**Comment by ayush-india** [comment]
but for that apprach we need to write all the extra args by hand.

**Comment by Veykril** [comment]
I'm not sure I understand what you mean, instead of setting `rust-analyzer.check.extraArgs` you'd be setting `rust-analyzer.cargo.extraArgs` (or both).

**Comment by ayush-india** [comment]
@Veykril i cannot find anything named `rust-analyzer.cargo.extraArgs`. 

Sorry if its sounds dumb.

>I'm not sure I understand what you mean

The issue i had was when i setted `rust-analyzer.check.extraArgs` to -r (as you can see in the issue) the problem i had was it made both a debug and release dir. And this pull should fix it (btw i am not a rust expert).

**Comment by Veykril** [comment]
> @Veykril i cannot find anything named `rust-analyzer.cargo.extraArgs`. 

It doesn't exist because thats what I am proposing in adding, the `check` settings should not affect build script building

**Comment by lnicola** [comment]
Of course it exists, it's [here](https://github.com/rust-lang/rust-analyzer/pull/14328/files#diff-00784dde03b1be151004f435a4ca74754cb674a9e789840e12760d8f3ac1728fR514).

**Comment by ayush-india** [comment]
@lnicola and @Veykril So it means that i can now use it by
**For neovim**
`local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
local lspconfig = require "lspconfig"
lspconfig.rust_analyzer.setup {
    on_attach = on_attach,
    settings = {["rust-analyzer"] = {cargo = {extraArgs = {"-r"}}}}
}`
**Vscode**
`rust-analyzer.cargo.extraArgs = ["-r"]`

When i clone @lnicola rust-analyzers repo and complie his build.. branch

Right, correct me if i am wrong

**Comment by lnicola** [comment]
Yes.

**Comment by ayush-india** [comment]
Just a random though: (till when will this feature get added to the "main" rust-analyzer)

**Comment by ayush-india** [comment]
Idk why i am writing this:

But if i use check.extraArgs it does not work but if i use cargo.extraArgs it does 

Thanks mate it fixed my problem (My thinkpad is alive again)

**Comment by ayush-india** [comment]
>But if i use check.extraArgs it does not work but if i use cargo.extraArgs it does

@lnicola Does not work if i restart my editor.

And then i have to recomplie the reelase dir.

And then it works

**Comment by lnicola** [comment]
Not sure I understand, which parameter are you setting?

**Comment by ayush-india** [comment]
@lnicola After my indepth research "lol" i find that 

When i use your ra it takes around 40s-90s to open ra after a reload (after the first cargo check -r ) but using the stock takes 30s .

But does not fix my problem (makes a debug and rlease dir but your ra does not).

and also takes around 9-11s to get a hover btw does not bother me. I just want only the release dir which your ra provides me.

Again Thanks mate

**Comment by ayush-india** [comment]
> Just a random though: (till when will this feature get added to the "main" rust-analyzer)

@lnicola can you also tell me this

**Comment by lnicola** [comment]
> When i use your ra it takes around 40s-90s to open ra after a reload (after the first cargo check -r ) but using the stock takes 30s .

`cargo check -r` will be slower. Is it also slow on a second load (it shouldn't be)? What if you comment out the setting?

> But does not fix my problem (makes a debug and rlease dir but your ra does not).

Yes, that's the point of this branch, to allow you to add that `-r` there.

> and also takes around 9-11s to get a hover btw does not bother me. I just want only the release dir which your ra provides me.

Should only happen on the first hover. There's no reason why my branch would be slower unless you've actually setting `-r` there, which makes the project load slower the first time. That is, unless you've built RA in the debug/dev profile, but you probably didn't.

> Just a random though: (till when will this feature get added to the "main" rust-analyzer)

Whenever Veykril has a chance to look again at this PR. If it's today, it will be even be in the version released tomorrow.

**Comment by ayush-india** [comment]
Thanks mate you have now answered all my question

Hoping the Veykril will look at this PR.

The rust community is (really really)*9999 helpful. Just hoped that every communtiy was this helpful. And also one more reason to love rust

**Review by Veykril — APPROVED** [review]

**Pull request merged**
