### PR TITLE
Stop eagerly resolving inlay hint text edits for VSCode

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Send less json over the wire.
After https://github.com/microsoft/vscode/issues/193124 was fixed, this change is not needed anymore.

VSCode 1.86.0 now supports double click for unresolved hint data too.

### CODE REVIEW

**Comment by lnicola** [comment]
You might need to rebase to fix the CI.

@davidbarsky what VS Code are you on?

**Comment by davidbarsky** [comment]
> You might need to rebase to fix the CI.
> 
> 
> 
> @davidbarsky what VS Code are you on?

1.78 right now, but 1.82 in a week or so. We can carry this as a patch, need be.

**Comment by Veykril** [comment]
Fwiw there is version field in the `InitializeParams` that a client can populate. Haven't checked but I'd expect that VSCode populates that. We could read that out and make this conditional on that for a few months. Otherwise if we merge this we should bump the VSCode requirement of the client extension so that we force people to upgrade their VSCode to contain the fix.

**Comment by SomeoneToIgnore** [comment]
I'm not in a rush and can hold this PR, as the whole point of it was to get rid of any code-specific checks.

But if you want to have it nonetheless, let me know and I will push more checks on top.

**Comment by Veykril** [comment]
Rebased (because of clippy issues that were fixed on master) and made the check conditional on the vscode version s owe can just merge it now.

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by Wilfred** [comment]
Looking at the upstream VS Code commit https://github.com/microsoft/vscode/commit/8adf59fc006880fb6a63830e9615f9d7686cabfe, I think the fix shipped in VS Code 1.86 FWIW.

**Comment by Veykril** [comment]
1.86 is what the code in the PR checks for

**Pull request merged**
