### PR TITLE
fix: add generic `TypeBoundList` in generated derivable impl

### LINKED ISSUE #13727: Incorrect PartialEq code assist
Given:
```rust
#[derive(PartialEq)]
enum Either<T, U> {
    Left(T),
    Right(U),
}
```

the code assist on `PartialEq` produces the following impl:
```rust
impl<T, U> PartialEq for Either<T, U> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Left(l0), Self::Left(r0)) => l0 == r0,
            (Self::Right(l0), Self::Right(r0)) => l0 == r0,
        }
    }
}
```
which is wrong in two ways:
1. There are no `PartialEq` bounds on the type arguments
2. There is no `_ => false` fallback case

The first one seems like it might be omitting the bounds either because it is easier to add custom bounds that way or because it's easier to implement, but the second issue seems like it would unequivocally be a bug and I'm surprised it would ever work like this.

**rust-analyzer version**: 0.4.1307-standalone

**rustc version**: rustc 1.66.0-nightly (a6b7274a4 2022-10-10)

### PR DESCRIPTION
**Pull request by rami3l**
Potentially fixes #13727.

Continuing with the work in #13732, this fix tries to add correct type bounds in the generated `impl` block:

```diff
  enum Either<T, U> {
      Left(T),
      Right(U),
  }
  
- impl<T, U> PartialEq for Either<T, U> {
+ impl<T: PartialEq, U: PartialEq> PartialEq for Either<T, U> {
      fn eq(&self, other: &Self) -> bool {
          match (self, other) {
              (Self::Left(l0), Self::Left(r0)) => l0 == r0,
              (Self::Right(l0), Self::Right(r0)) => l0 == r0,
              _ => false,
          }
      }
  }
```

### CODE REVIEW

**Comment by rami3l** [comment]
This fix does influence [this testcase](https://github.com/rust-lang/rust-analyzer/actions/runs/3682289492/jobs/6229791808#step:8:325) and friends, but I really cannot decide if this is expected behavior or not now...

```diff
  struct Foo<'a, T: Foo<'a>> {}
  
- impl<'a, T> Foo<'a, T> {
+ impl<'a, T: Foo<'a>> Foo<'a, T> {
      $0
  }
```

**Comment by rami3l** [comment]
@lowr Thanks a lot for your reply!

However, there are still several points that I'm unsure about:

1. > add the bounds after generating impl text

    I'm not quite clear about what you meant by this.
If you meant appending `where` bounds after the first line, then that's also part of `fn generate_impl_text_inner()`'s job:

    https://github.com/rust-lang/rust-analyzer/blob/4596847a88abb0d5077c5111c3093e724673d7a0/crates/ide-assists/src/utils.rs#L499-L502


2. > We may also want to check if the bounds already include the trait we're adding so it wouldn't be duplicated.

    This logic has already been handled in the `make::type_bound_list` function:

    ```rs
    let bounds = bounds.into_iter().map(|it| it.to_string()).unique().join(" + ");
    ```

    I assume it's not desired to make a `BoundList` with duplicates anyway, plus the duplication is detected by `.to_string()`, so I put this logic in the constructor.

    And there's an existing test guarding against duplications:

    https://github.com/rust-lang/rust-analyzer/blob/4596847a88abb0d5077c5111c3093e724673d7a0/crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs#L1182-L1201

    I'll add a new test case with more bounds to showcase the reservation of existing ones as well as the deduplication, just in case :)

**Comment by lowr** [comment]
> 1. > add the bounds after generating impl text
>        
>        
> I'm not quite clear about what you meant by this.
> If you meant appending `where` bounds after the first line, then that's also part of `fn generate_impl_text_inner()`'s job:

I meant you can add the bounds in `impl_def_from_trait()` after calling `generate_trait_impl_text()`, maybe around [here](https://github.com/rust-lang/rust-analyzer/blob/4596847a88abb0d5077c5111c3093e724673d7a0/crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs#L196-L198), by directly mutating the AST in-place. See [this file](https://github.com/rust-lang/rust-analyzer/blob/4596847a88abb0d5077c5111c3093e724673d7a0/crates/syntax/src/ast/edit_in_place.rs) if you haven't seen our AST editing API (I'm not sure if we have the API for editing bounds, you may have to add one).

`generate_impl_text_inner()` is just a utility function after all and I'd say its job is to generate the most generic impl text that can be used in multiple assists as a "starting point", which then you can mutate depending on your needs. Some assists, like `generate_from_impl_for_enum`, don't need to add trait bounds, and some may want to add bounds to only one type parameter among many. These logics are specific to each assist thus it's for them to handle themselves, not for `generate_impl_text_inner()` to.

That said, cece895ccdcafe7ec9412cf92f955032c79851d7 actually looks good enough (though special casing `$0` still bugs me a bit), and I don't strongly oppose to this getting merged if maintainers approve.

> 2. > We may also want to check if the bounds already include the trait we're adding so it wouldn't be duplicated.
>   
>   
>   This logic has already been handled in the `make::type_bound_list` function:

Aha, this is clearly my oversight, sorry about that. Nice work! :+1:

**Comment by rami3l** [comment]
@lowr I see what you mean now, thanks 🙏

Let's wait for the moment and see what the maintainers have to say about this change then.

**Comment by Veykril** [comment]
This seems fine to me, a more general API would be in having the boolean parameter be replaced with a list of bound lists that zip up with the generic parameters, but as that is currently not really needed there is no point in going that far.
Mutating the ast would also work but that is always kind of a pain to work with.
@bors r+

**Pull request merged**
