### PR TITLE
minor: sync from downstream

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by HKalbasi** [comment]
This contains a change to some commented code in layout, which makes me wonder: is it possible to use auto published crates on this repository, but depending on rustc internals when r-a is a subtree? With this, it would always build with the latest version of rustc crates and we can bump them without any breakage.

**Comment by Veykril** [comment]
I don't think we can conditionally use path dependencies

**Comment by lnicola** [comment]
I guess we can patch `Cargo.toml` in `x.py`? But it seems pretty iffy either way.

**Pull request merged**
