### PR TITLE
Add more methods for resolving definitions from AST to their corresponding HIR types

### PR DESCRIPTION
**Pull request by regexident**
In order to be able to add these methods with consistent naming I had to also rename two existing methods that would otherwise be conflicting/confusing:

`Semantics::to_module_def(&self, file: FileId) -> Option<Module>` (before)
`Semantics::file_to_module_def(&self, file: FileId) -> Option<Module>` (after)

`Semantics::to_module_defs(&self, file: FileId) -> impl Iterator<Item = Module>` (before)
`Semantics::file_to_module_defs(&self, file: FileId) -> impl Iterator<Item = Module>` (after)

(the PR is motivated by an outside use of the `ra_ap_hir` crate that would benefit from being able to walk a `hir::Function`'s AST, resolving its exprs/stmts/items to their HIR equivalents)

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Comment by regexident** [comment]
Bots having a moment? 😅

**Comment by Veykril** [comment]
bors is always having a moment

**Pull request merged**
