### PR TITLE
Initial support for implicit drop inlay hint

### PR DESCRIPTION
**Pull request by HKalbasi**
cc #15785

### CODE REVIEW

**Comment by lnicola** [comment]
image

**Comment by rben01** [comment]
Would it be possible for these to go above the statement they precede instead of to the left? Shifting a line right to make room for the `drop` inlay hint doesn't look so nice. For me, it'd be preferable to have the `drop` visible when hovering over the `return` or the `}`.

**Comment by Veykril** [comment]
Unlikely, this is a limitation by the language server protocol. And VSCode doesnt support ghost text between lines either (only annotations but those dont work that well for this purpose)

**Pull request merged**
