### PR TITLE
feat: Add trailing `;` when typing `=` in assignment

### PR DESCRIPTION
**Pull request by jonas-schievink**
Peek 2022-04-12 19-41

This does have a false positive to keep in mind, it will add a trailing `;` in the following snippet too, which is probably not desired:

```rust
fn is_zero(i: i32) -> bool {
    i $0 0
}
```

However, that function is unlikely to be written from the "inside out" like that, so it might be acceptable. Typically `=` is only inserted last when the author realizes that an existing expression should be assigned to some variable.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
> I mean we could check the expected type in that position maybe?

That could work, but this is a synchronous request, so running type inference in there will block typing

**Comment by HKalbasi** [comment]
Is it possible to remove the semicolon on the second `=`?

**Comment by Veykril** [comment]
> That could work, but this is a synchronous request, so running type inference in there will block typing

Right, let's not do that then :)

> Is it possible to remove the semicolon on the second =?

This might be a good idea though

**Comment by jonas-schievink** [comment]
This seems to work pretty well. We should probably make every individual feature here configurable though.

@bors r+

**Pull request merged**
