### PR TITLE
Changed Logo

### PR DESCRIPTION
**Pull request by electrolyte-orb**
Have redesigned the Logo.

### CODE REVIEW

**Comment by lnicola** [comment]
Those look pretty cool (the `io:` in the square one bugs me, though), but I'm not sure who can decide here :smile:.

CC @matklad

**Comment by electrolyte-orb** [comment]
> Those look pretty cool (the `io:` in the square one bugs me, though), but I'm not sure who can decide here 😄.
> 
> CC @matklad

That is why I LOVE OPEN SOURCE 😉

PS: give me suggestions for that `io`

**Comment by matklad** [comment]
Hm, to be fair, I am not sure this is an improvement. It does look nice, and is somewhat more evocative of the code-completion metaphor, but at the same time it contains a lot more of finer details than the old logo, and I think it's relatively important for logos to be simple and legible even at small size. 

At the same time, yeah, now that we are an official rust project, it porbably makes sense to incorporate Rust's gear in some way. Schematically, what about something like `Ⓡ._`, that is, "completing Rust"? 

Id' probably also open a bikeshed thread on internals to gather feedback from community here.

**Comment by matklad** [comment]
cc https://github.com/rust-lang/cargo/issues/4446 and  https://internals.rust-lang.org/t/opinion-changing-rusts-logo-would-have-a-big-benefit/17654

**Comment by flodiebold** [comment]
Maybe to add to that, I think there shouldn't be any other text than `rust-analyzer` in the logo -- that's why having it be the name that's being completed it's nice. The `io::` is rather confusing.

**Comment by electrolyte-orb** [comment]
# Take a look
NEW logo-square
NEW logo-wide2

**Comment by Veykril** [comment]
Sorry but the way your replies are written makes it hard to consider this seriously. As matklad pointed out, it might be better to raise a proper discussion for this first either as an issue or an IRLO thread. I think we definitely want to touch up on the logo but it's anything but an easy decision on where to go with the logo for r-a and what to present on it.

**Comment by electrolyte-orb** [comment]
Okay, If you are in for a discussion, then I will provide the Figma design files for the 4 logos I've submitted.
Also the design tokens, like colors and grid will be within those files (feel free to pass it on to different designers).

**Comment by Yatekii** [comment]
Does the rust analyzer need a specific logo? I mean sure it would be nice for the website, but wouldn't it be good to incooperate it into the official Rust website anways? Plus, the logo shows up in VSCode. To recognize the now-official Rust plugin, it would make sense imo to just use the Rust logo itself.

**Comment by jowsey** [comment]
> To recognize the now-official Rust plugin, it would make sense imo to just use the Rust logo itself.

I generally agree, though it might end up looking too similar to the deprecated "Rust" plugin which still shows up above r-a in VS Code's plugin search, which could cause some confusion?

**Comment by Yatekii** [comment]
> though it might end up looking too similar to the deprecated "Rust" plugin

I would make it a black logo like everywhere. The racer based plugin is still rusty in color plus the plugin says "deprecated". Can't we yank it? I thought that's possible.

**Comment by Veykril** [comment]
Let's close this in favor of https://github.com/rust-lang/rust-analyzer/issues/13651 for now

**Pull request closed without merging**
