### PR TITLE
feat: Improved inline_call to replace `Self`

### LINKED ISSUE #13060: Minor problem of inlining methods
**rust-analyzer version**: rust-analyzer version: 0.4.1173-standalone (82ff74050 2022-08-17)

**rustc version**: N/A

**relevant settings**: N/A

Code:

```rust
struct A(u32);
impl A {
    fn test() -> Self { Self(114514) }
}
fn main() {
    A::test();
}
```

Hit inline on `A::test` call, it generates

```rust
fn main() {
    Self(114514);
}
```

I expect `Self` to be substituted.

### PR DESCRIPTION
**Pull request by ice1000**
Fixes #13060

### CODE REVIEW

**Comment by lowr** [comment]
Does this also fix #10291?

**Comment by Veykril** [comment]
It should fix that one as well yes
@bors r+

**Comment by lowr** [comment]
Nice, #10291 should be closed too then.

**Comment by ice1000** [comment]
There is one more complication: if the inline target is also in the impl block then Self should be preserved (I guess)

**Pull request merged**
