### PR TITLE
Bump `rustc-perf` checkout for metrics, replace webrender, diesel and ripgrep with newer versions

### PR DESCRIPTION
**Pull request by Veykril**
The previous versions were removed hence the updates. The metric results for the changed ones are disconnected now as to not muddle things up.

I think it's worth it for us to occasionally bump the `rustc-perf` checkout, as it allows us to include more interesting new targets.

Notably, the newer diesel is 3 times as fast to analyze as the one of the current checkout.

### CODE REVIEW

**Comment by Veykril** [comment]
r? @lnicola (since you've seen it already :^)

Gonna check how much time we get back to spent on new targets after this has been merged

**Review by lnicola — APPROVED** [review]
Looks good, as far as I can tell by looking on my phone, but I didn't actually check the paths etc.

**Comment by Veykril** [comment]
I added an assert that checks the paths (otherwise we do perf on the rustc-perf repo instead if the path is mistyped thanks to how our discovery works 😅), so they are good

@bors r=lnicola

**Comment by Veykril** [comment]
Had to change CI to pick up the new files
@bors r+

**Pull request merged**
