### PR TITLE
Implement lifetime inferring

### PR DESCRIPTION
**Pull request by dfireBird**

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Comment by flodiebold** [comment]
@bors r+

thanks!

**Comment by Veykril** [comment]
This regressed unknown types from 41 to 62 on self somehow 🤔

**Comment by dfireBird** [comment]
There shouldn't be anything creating new `TyKind::Error`. I'll check on that. Meanwhile, if you want to revert that commit we can.

**Comment by Veykril** [comment]
It's fine, it only regressed on self so its likely not too bad. I imagine unification fails due to some new lifetimes now within chalk

**Pull request merged**
