### PR TITLE
chore: fix a few spans without `.entered()`

### PR DESCRIPTION
**Pull request by davidbarsky**

### CODE REVIEW

**Comment by lnicola** [comment]
I might have found a couple more, can you take a look?

 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir-ty/src/inhabitedness.rs#L18
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir-ty/src/inhabitedness.rs#L33
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/lib.rs#L242
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/lib.rs#L4497
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/lib.rs#L4585
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/lib.rs#L4652
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/lib.rs#L4660
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/semantics.rs#L725
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/semantics.rs#L1362
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/semantics/source_to_def.rs#L121
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/semantics/source_to_def.rs#L136
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/hir/src/semantics/source_to_def.rs#L161
 - https://github.com/rust-lang/rust-analyzer/blob/dcbb27aab60eac01a666a2d12a64683a8f237e8b/crates/ide-assists/src/handlers/add_missing_impl_members.rs#L108

**Comment by davidbarsky** [comment]
oh, good catch! nice.

**Comment by Veykril** [comment]
That might explain some confusing traces I've seen, thank you!
@bors r+

**Review by lnicola — APPROVED** [review]

**Pull request merged**
