### PR TITLE
Add syntax fixup for while loops

### PR DESCRIPTION
**Pull request by palango**
Part of https://github.com/rust-lang/rust-analyzer/issues/12777

This is a first iteration to gather some feedback. In particular I'm not sure if the curly braces should be added here, but I couldn't get the test to work without them. Any hints welcome!

### CODE REVIEW

**Comment by flodiebold** [comment]
Thanks for looking into this!

We should only add the curly braces if they're missing, similar to how we do it for `if`. You can check whether the loop body is missing with `it.loop_body().is_none()`. I'd add two more test cases: `while {}` and `while foo`. (Possibly we actually parse `while {}` as having a condition, but no loop body? In that case adding `{}` is also fine though.)

**Comment by palango** [comment]
@flodiebold Thanks for the hints!

I added the test cases you asked for, but there's something weird happening in `fixup_while_3` (run with `cargo test -p hir-expand while_3 -- --nocapture`):
```
running 1 test
Found while
Found condition: Some(BlockExpr(BlockExpr { syntax: BLOCK_EXPR@22..24 }))
Found loop body: Some(BlockExpr { syntax: BLOCK_EXPR@22..24 })
thread 'fixup::tests::fixup_while_3' panicked at 'assertion failed: `(left == right)`
  left: `[SyntaxError("expected a block", 15..15)]`,
 right: `[]`: parse has syntax errors. parse tree:
MACRO_ITEMS@0..16
  FN@0..16
    FN_KW@0..2 "fn"
    NAME@2..5
      IDENT@2..5 "foo"
    PARAM_LIST@5..7
      L_PAREN@5..6 "("
      R_PAREN@6..7 ")"
    BLOCK_EXPR@7..16
      STMT_LIST@7..16
        L_CURLY@7..8 "{"
        WHILE_EXPR@8..15
          WHILE_KW@8..13 "while"
          BLOCK_EXPR@13..15
            STMT_LIST@13..15
              L_CURLY@13..14 "{"
              R_CURLY@14..15 "}"
        R_CURLY@15..16 "}"
', crates/hir-expand/src/fixup.rs:452:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test fixup::tests::fixup_while_3 ... FAILED

failures:

failures:
    fixup::tests::fixup_while_3

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 18 filtered out; finished in 0.00s
```

It seems like the curly braces are parsed both as the condition and the loop body.

**Comment by flodiebold** [comment]
Oh... yeah, currently for `while {}` we treat the block as both the condition and the loop body. We shouldn't do that. I think we'll need to replace the autogenerated `condition` method by something like the following:
```rust
    pub fn condition(&self) -> Option<Expr> {
        let mut exprs = support::children(self.syntax());
        let first = exprs.next();
        let second = exprs.next();
        if let Some(ast::Expr::BlockExpr(_)) = first {
            second.and(first)
        } else {
            first
        }
    }
```
i.e. if the first expression is a block expression, only consider it as the condition if there's also a second one (i.e. the loop body). This would live in an `impl ast::WhileExpr` in `node_ext.rs`, and we'd need to modify the `generate_nodes` function in `sourcegen_ast.rs` to skip this method, similar to how we already skip the `HasLoopBody` trait. I think we'll actually have a similar problem with `for`...

@lnicola @Veykril any better ideas?

**Comment by Veykril** [comment]
Hmm, I would expect with `while {}` that the `{}` is the condition, since that is the first expression, and as such that we have no body.

**Comment by lnicola** [comment]
Yeah, but it's less common to use blocks for the condition ([oh, hello there!](https://gist.github.com/huonw/8435502)), isn't it? In practice I kinda' doubt it matters.

CC https://github.com/rust-lang/rust-analyzer/pull/11565, #11561.

**Comment by flodiebold** [comment]
It certainly doesn't matter for this, but it might matter for some other features like completion? In any case, I think treating the `{}` as the condition wouldn't make this significantly easier anyway.

**Comment by Veykril** [comment]
Ye, that's the thing. It's barely used so assuming the condition is what's missing helps more in the general case I'd say let's special case it.

In any case, we'll have to add `iterable` (for loops) and `condition` (while loops) here https://github.com/Veykril/rust-analyzer/blob/c8ff70e924efe3adba39ac5dc2a93dbd94bde5a4/crates/syntax/src/tests/sourcegen_ast.rs#L671-L685

This will also require `condition` for `IfExpr` and `MatchGuard` to be implemented manually then. (We should revisit the source gen script for this at some point, it's getting a bit messy I think)

**Comment by palango** [comment]
Some of the things you've been discussing are over my head for now and should probably be split out in a new issue.

Would it be ok to remove the test case in question and wait until the underlying issue is fixed?
```rust
fn foo() {
    while {}
}
```

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust-analyzer/pull/12890 should address the syntax tree problems, that is we no longer should be treating a single expression as both the condition and the body

**Comment by palango** [comment]
> #12890 should address the syntax tree problems, that is we no longer should be treating a single expression as both the condition and the body

Thanks for the quick fix, that solved the problem.

**Pull request merged**
